Repository gluesql/gluesql, pull requests merged in 2021-12, with the labels that each got.

#396 385 factorial operator
  src/ast/operator.rs
  src/data/value/error.rs
  src/data/value/mod.rs
  src/executor/evaluate/evaluated.rs
  src/executor/evaluate/expr.rs
  src/tests/error.rs
  src/tests/mod.rs
  src/tests/unary_operator.rs
  src/translate/error.rs
  src/translate/operator.rs
Labels: enhancement

#414 Support CTAS(Create Table As Select ~) statement
  src/ast/mod.rs
  src/executor/alter/error.rs
  src/executor/alter/table.rs
  src/executor/execute.rs
  src/tests/alter/create_table.rs
  src/translate/mod.rs
Labels: enhancement

#377 Adding data type: Decimal
  Cargo.toml
  src/ast/data_type.rs
  src/data/value/big_edian.rs
  src/data/value/error.rs
  src/data/value/group_key.rs
  src/data/value/into.rs
  src/data/value/literal.rs
  src/data/value/mod.rs
  src/data/value/unique_key.rs
  src/executor/aggregate/hash.rs
  src/executor/validate.rs
  src/tests/data_type/decimal.rs
  src/tests/data_type/mod.rs
  src/tests/mod.rs
  src/translate/data_type.rs
Labels: enhancement

#407 Add int8 data type
  src/ast/data_type.rs
  src/data/bigdecimal_ext.rs
  src/data/interval/primitive.rs
  src/data/value/big_edian.rs
  src/data/value/binary_op/f64.rs
  src/data/value/binary_op/i64.rs
  src/data/value/binary_op/i8.rs
  src/data/value/binary_op/mod.rs
  src/data/value/error.rs
  src/data/value/group_key.rs
  src/data/value/into.rs
  src/data/value/literal.rs
  src/data/value/mod.rs
  src/data/value/unique_key.rs
  src/executor/aggregate/hash.rs
  src/executor/validate.rs
  src/tests/data_type/int8.rs
  src/tests/data_type/mod.rs
  src/tests/mod.rs
  src/translate/data_type.rs
Labels: enhancement

#433 Support arithmetic operations for decimal and null
  src/data/value/mod.rs
Labels: good first issue, improvement

#435 Move `order_by` from query to select
  src/ast/query.rs
  src/executor/execute.rs
  src/executor/select/mod.rs
  src/plan.rs
  src/translate/query.rs
Labels: improvement

#434 Add missing assert macro
  src/data/value/mod.rs
Labels: bug

#438 Add `Metadata` optional store trait,
  Cargo.toml
  src/ast/mod.rs
  src/executor/execute.rs
  src/executor/mod.rs
  src/lib.rs
  src/storages/memory_storage/metadata.rs
  src/storages/memory_storage/mod.rs
  src/storages/sled_storage/metadata.rs
  src/storages/sled_storage/mod.rs
  src/store/metadata.rs
  src/store/mod.rs
  src/tests/metadata.rs
  src/tests/mod.rs
  src/tests/transaction/metadata.rs
  src/tests/transaction/mod.rs
  src/translate/error.rs
  src/translate/mod.rs
  tests/memory_storage.rs
  tests/sled_storage.rs
  tests/sled_transaction.rs
Labels: enhancement

#440 Implement CLI application
  .github/workflows/coverage.yml
  .gitignore
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/helper.rs
  cli/src/main.rs
  cli/src/print.rs
Labels: enhancement

#441 Move `join_columns` argument from `Join::apply()` to `Join::new()`
  core/src/executor/join.rs
  core/src/executor/select/mod.rs
Labels: enhancement

#443 Change from `cli/target` to `<general>/target` in ignore,
  .gitignore
Labels: improvement

#444 Bump rust version to 1.57
  core/src/data/interval/mod.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  rust-toolchain
  test-suite/src/data_type/date.rs
  test-suite/src/data_type/time.rs
  test-suite/src/default.rs
Labels: improvement

#445 Repair broken links in README
  README.md
Labels: improvement
