Repository gluesql/gluesql, pull requests merged in 2021-02, with the labels that each got.

#141 Implement UNIQUE constraint in CREATE TABLE
  src/data/table.rs
  src/data/value.rs
  src/executor/create_table.rs
  src/executor/execute.rs
  src/executor/mod.rs
  src/executor/update.rs
  src/executor/validate.rs
  src/result.rs
  src/tests/create_table.rs
  src/tests/mod.rs
  src/tests/unique.rs
Labels: enhancement

#142 Make codes clippy clean
  src/data/value.rs
  src/executor/filter.rs
Labels: bug

#137 Add Documentation
  book/.gitignore
  book/book.toml
  book/src/SUMMARY.md
  book/src/community.md
  book/src/contributing.md
  book/src/contributors.md
  book/src/crate_docs.md
  book/src/examples.md
  book/src/features.md
  book/src/hello_world.md
  book/src/installation.md
  book/src/internal.md
  book/src/introduction.md
  book/src/sled_multi_threaded.md
  book/src/type_errors.md
  examples/hello_world.rs
  examples/sled_multi_threaded.rs
Labels: documentation, enhancement

#143 Strict table types
  src/data/value.rs
  src/executor/validate/mod.rs
  src/executor/validate/unique.rs
  src/tests/error.rs
  src/tests/mod.rs
  src/tests/validate/mod.rs
  src/tests/validate/types.rs
  src/tests/validate/unique.rs
Labels: enhancement

#145 Single Quotes
  src/data/value.rs
  src/tests/sql_types.rs
Labels: enhancement
