Repository gluesql/gluesql, pull requests merged in 2021-03, with the labels that each got.

#144 CAST
  src/data/mod.rs
  src/data/value/ast_value.rs
  src/data/value/error.rs
  src/data/value/mod.rs
  src/executor/evaluate/error.rs
  src/executor/evaluate/evaluated.rs
  src/executor/evaluate/mod.rs
  src/result.rs
  src/tests/function/cast.rs
  src/tests/function/mod.rs
  src/tests/mod.rs
Labels: enhancement

#162 Change literal casting function to return from AstValue to Value,
  src/data/mod.rs
  src/data/value/ast_value.rs
  src/data/value/error.rs
  src/data/value/mod.rs
  src/executor/evaluate/error.rs
  src/executor/evaluate/evaluated.rs
  src/tests/function/cast.rs
  src/tests/mod.rs
Labels: bug, enhancement

#163 Update Value->cast to support nullable types,
  src/data/value/mod.rs
  src/tests/function/cast.rs
Labels: enhancement

#157 LEFT and RIGHT functions
  src/executor/evaluate/error.rs
  src/executor/evaluate/mod.rs
  src/tests/function/left_right.rs
  src/tests/function/mod.rs
  src/tests/function/upper_lower.rs
  src/tests/mod.rs
Labels: enhancement

#169 Replace Value::Opt- and Empty to Value::Null!
  src/data/value/ast_value.rs
  src/data/value/group_key.rs
  src/data/value/mod.rs
  src/data/value/unique_key.rs
  src/executor/aggregate/hash.rs
  src/executor/aggregate/state.rs
  src/executor/context/blend_context.rs
  src/executor/evaluate/mod.rs
  src/executor/update.rs
  src/executor/validate/unique.rs
  src/tests/aggregate.rs
  src/tests/alter_table.rs
  src/tests/default.rs
  src/tests/function/cast.rs
  src/tests/function/left_right.rs
  src/tests/function/upper_lower.rs
  src/tests/join.rs
  src/tests/macros.rs
  src/tests/nullable.rs
  src/tests/tester.rs
  src/tests/validate/unique.rs
Labels: enhancement

#173 Remove fake unreachable errors in EvaluateError
  src/executor/evaluate/error.rs
  src/executor/evaluate/evaluated.rs
  src/tests/arithmetic.rs
  src/tests/nullable.rs
Labels: bug

#183 Fix type validation to check all possible branches from INSERT & UPDATE
  src/data/mod.rs
  src/data/row.rs
  src/data/schema.rs
  src/data/value/error.rs
  src/data/value/mod.rs
  src/executor/execute.rs
  src/executor/update.rs
  src/executor/validate.rs
  src/executor/validate/mod.rs
  src/storages/sled_storage/alter_table.rs
  src/tests/validate/types.rs
Labels: bug

#184 Add validation to CREATE & ALTER TABLE
  src/executor/alter/alter_table.rs
  src/executor/alter/create_table.rs
  src/executor/alter/drop.rs
  src/executor/alter/error.rs
  src/executor/alter/mod.rs
  src/executor/alter/validate.rs
  src/executor/create_table.rs
  src/executor/execute.rs
  src/executor/mod.rs
  src/result.rs
  src/tests/alter_table.rs
  src/tests/create_table.rs
  src/tests/drop_table.rs
  src/tests/error.rs
Labels: enhancement

#185 Fix CREATE TABLE IF NOT EXISTS not to call insert_schema when existin…
  src/executor/alter/create_table.rs
  src/tests/create_table.rs
Labels: bug
