Repository gluesql/gluesql, pull requests merged in 2022-05, with the labels that each got.

#530 Decimal math
  core/src/data/value/binary_op/decimal.rs
  core/src/data/value/binary_op/f64.rs
  core/src/data/value/binary_op/i64.rs
  core/src/data/value/binary_op/i8.rs
  core/src/data/value/binary_op/mod.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/result.rs
  test-suite/Cargo.toml
  test-suite/src/data_type/decimal.rs
Labels: enhancement

#512 GlueSQL.js - support both web browsers and Node.js
  .github/workflows/coverage.yml
  Cargo.toml
  core/Cargo.toml
  gluesql-js/.gitignore
  gluesql-js/README.md
  gluesql-js/examples/nodejs/main.js
  gluesql-js/examples/web/module/index.html
  gluesql-js/examples/web/rollup/index.html
  gluesql-js/examples/web/rollup/main.js
  gluesql-js/examples/web/rollup/package.json
  gluesql-js/examples/web/rollup/rollup.config.js
  gluesql-js/examples/web/webpack/index.html
  gluesql-js/examples/web/webpack/main.js
  gluesql-js/examples/web/webpack/package.json
  gluesql-js/examples/web/webpack/webpack.config.js
  gluesql-js/gluesql.js
  gluesql-js/gluesql.node.js
  gluesql-js/index.html
  gluesql-js/package.json
  gluesql-js/web/.gitignore
  gluesql-js/web/Cargo.toml
  gluesql-js/web/README.md
  gluesql-js/web/gluesql.js
  gluesql-js/web/package.json
  gluesql-js/web/rollup.config.js
  gluesql-js/web/src/lib.rs
  gluesql-js/web/src/payload.rs
  gluesql-js/web/src/utils.rs
  gluesql-js/web/tests/memory_storage.rs
  gluesql-js/web/tests/payload.rs
  gluesql-js/web/webdriver.json
Labels: enhancement

#543 Fix gluesql-js/package.json to publish files correctly,
  gluesql-js/README.md
  gluesql-js/examples/web/webpack/index.html
  gluesql-js/package.json
Labels: bug

#529 implement cast to decimal
  core/src/data/value/error.rs
  core/src/data/value/into.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  test-suite/src/function/cast.rs
Labels: enhancement

#547 Implement SledStorage export & import features
  storages/sled-storage/src/error.rs
  storages/sled-storage/src/lib.rs
  storages/sled-storage/src/lock.rs
  storages/sled-storage/src/store.rs
  storages/sled-storage/src/store_mut.rs
  storages/sled-storage/src/transaction.rs
  storages/sled-storage/tests/export_and_import.rs
Labels: enhancement

#546 cast 255 as int8, should return an error, but returns 127 instead (resolves issue #545)
  core/src/data/value/error.rs
  core/src/data/value/literal.rs
  test-suite/src/function/cast.rs
Labels: improvement

#542 Migrate code from sqlparser v14 to v16
  core/Cargo.toml
  core/src/translate/ast_literal.rs
  core/src/translate/error.rs
  core/src/translate/expr.rs
  test-suite/src/error.rs
Labels: improvement

#552 Clean up gluesql-js/ build scripts,
  gluesql-js/package.json
  gluesql-js/web/README.md
  gluesql-js/web/package.json
Labels: documentation, improvement

#559 Fix the link in `gluesql-js/README.md` Webpack example
  gluesql-js/README.md
Labels: documentation

#557 Update rusttoolchain version to 1.60 and sqlparser-rs to 0.17
  core/Cargo.toml
  rust-toolchain
Labels: improvement

#565 Replace the `to_string` macro with the `serialize_all` macro
  core/Cargo.toml
  core/src/ast/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
Labels: improvement

#551 Show indexes from table... (resolves issue #520)
  cli/src/print.rs
  core/src/ast/mod.rs
  core/src/data/schema.rs
  core/src/executor/execute.rs
  core/src/translate/mod.rs
  test-suite/src/index/mod.rs
  test-suite/src/index/showindexes.rs
  test-suite/src/lib.rs
Labels: enhancement

#571 use checked_x functions for i8, i64 and decimal data types so that we don't panic during an overflow
  core/src/data/interval/primitive.rs
  core/src/data/value/binary_op/decimal.rs
  core/src/data/value/binary_op/i64.rs
  core/src/data/value/binary_op/i8.rs
  core/src/data/value/into.rs
  core/src/data/value/mod.rs
Labels: improvement

#575 have datatype enum use SCREAMING_SNAKE_CASE
  cli/src/print.rs
  core/src/ast/data_type.rs
Labels: improvement

#576 Fix modulo binary op to handle zero divisor correctly
  core/src/data/value/mod.rs
Labels: bug

#577 Replace MemoryStorage Key to core::data::Key,
  core/src/data/key.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/src/index.rs
  storages/memory-storage/src/lib.rs
  storages/memory-storage/tests/memory_storage.rs
Labels: improvement

#564 upgrade to rust 1.61
  rust-toolchain
Labels: improvement

#578 Fix rust clippy gh action to check optional features
  .github/workflows/rust.yml
  core/src/executor/execute.rs
Labels: bug, improvement

#585 Fix PartialEq between f64 and other numeric types
  core/src/data/value/binary_op/f64.rs
  core/src/data/value/binary_op/i64.rs
  core/src/data/value/binary_op/i8.rs
Labels: improvement

#584 Use const `Dialect` in parse_query
  core/src/parse_sql.rs
Labels: improvement

#580 Fix `sled_multi_threaded` example code with threads of `INSERT` and `SELECT`,
  .github/workflows/rust.yml
  examples/sled_multi_threaded.rs
Labels: bug

#573 Fix primitive numeric types cast not to panic
  core/src/data/value/into.rs
Labels: improvement

#586 Add BYTEA data type support
  core/Cargo.toml
  core/src/ast/ast_literal.rs
  core/src/ast/data_type.rs
  core/src/data/key.rs
  core/src/data/literal.rs
  core/src/data/value/big_endian.rs
  core/src/data/value/error.rs
  core/src/data/value/into.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/translate/ast_literal.rs
  core/src/translate/data_type.rs
  test-suite/Cargo.toml
  test-suite/src/alter/create_table.rs
  test-suite/src/data_type/bytea.rs
  test-suite/src/data_type/mod.rs
  test-suite/src/data_type/uuid.rs
  test-suite/src/lib.rs
Labels: enhancement

#588 Replace SledStorage generic key T from IVec to data::Key
  core/src/data/key.rs
  core/src/data/value/big_endian.rs
  core/src/data/value/mod.rs
  storages/sled-storage/src/index.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/lib.rs
  storages/sled-storage/src/store.rs
  storages/sled-storage/src/store_mut.rs
  storages/sled-storage/tests/sled_storage.rs
Labels: improvement
