Repository gluesql/gluesql, pull requests merged in 2022-09, with the labels that each got.

#730 Support `ORDER BY` clause in `VALUES list`
  core/src/ast/query.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/root.rs
  core/src/executor/select/mod.rs
  core/src/executor/sort.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/primary_key.rs
  core/src/plan/schema.rs
  core/src/translate/query.rs
  test-suite/src/values.rs
Labels: enhancement

#807 [AST] To_sql for CREATE TABLE, ALTER TABLE
  core/src/ast/ddl.rs
  core/src/ast/mod.rs
Labels: enhancement

#808 [AST Builder] Combine in_list and in_subquery into in_list
  core/src/ast_builder/expr/in_list.rs
  core/src/ast_builder/expr/in_subquery.rs
  core/src/ast_builder/expr/mod.rs
Labels: improvement

#784 [AST-Builder] Create Table Statement
  core/src/ast_builder/column_def.rs
  core/src/ast_builder/create_table.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/table.rs
  core/src/parse_sql.rs
  core/src/translate/mod.rs
Labels: enhancement

#783 Enhance the coverage of `operator.rs`
  core/src/ast/expr.rs
  core/src/ast/operator.rs
Labels: improvement

#813 [AST Builder] Implement Alter table statement
  core/src/ast_builder/alter_table.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/table.rs
Labels: enhancement

#816 [Test Suite] unify order of test arguments
  test-suite/src/aggregate/error.rs
  test-suite/src/arithmetic/error.rs
Labels: improvement

#817 Migrate sqlparser-rs from 0.18 to 0.19,
  core/Cargo.toml
  core/src/ast/expr.rs
  core/src/ast_builder/expr/exists.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/mod.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/planner.rs
  core/src/translate/ast_literal.rs
  core/src/translate/data_type.rs
  core/src/translate/error.rs
  core/src/translate/expr.rs
  core/src/translate/mod.rs
  test-suite/src/data_type/interval.rs
  test-suite/src/tester/mod.rs
Labels: improvement

#821 [AST] Implement to_sql for INSERT, UPDATE, DELETE
  core/src/ast/mod.rs
Labels: improvement

#819 Upgrade sqlparser-rs to v0.22
  core/Cargo.toml
  core/src/ast/expr.rs
  core/src/ast/mod.rs
  core/src/ast/operator.rs
  core/src/ast_builder/expr/binary_op.rs
  core/src/ast_builder/expr/like.rs
  core/src/ast_builder/expr/mod.rs
  core/src/executor/evaluate/expr.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/mod.rs
  core/src/plan/join.rs
  core/src/plan/planner.rs
  core/src/plan/primary_key.rs
  core/src/translate/expr.rs
  core/src/translate/function.rs
  core/src/translate/mod.rs
  core/src/translate/operator.rs
  test-suite/src/filter.rs
  test-suite/src/function/trim.rs
  test-suite/src/lib.rs
  test-suite/src/like_ilike.rs
  test-suite/src/nested_select.rs
Labels: improvement

#824 [AST] to_sql for STATEMENTS
  core/src/ast/mod.rs
Labels: improvement

#805 Support ORDER BY `ALIAS` and `COLUMN_INDEX`
  core/src/executor/context/blend_context.rs
  core/src/executor/context/mod.rs
  core/src/executor/join.rs
  core/src/executor/mod.rs
  core/src/executor/select/mod.rs
  core/src/executor/sort.rs
  core/src/result.rs
  test-suite/src/order_by.rs
Labels: enhancement

#818 [Function] Implement `FORMAT` function
  core/src/ast/function.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/format.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#826 [Test suite] Add insert integration test
  test-suite/src/insert.rs
  test-suite/src/lib.rs
Labels: improvement

#831 Simplify root doc comment code example
  src/lib.rs
Labels: documentation

#830 Replace crate::`comfy-table` with `tabled`
  cli/Cargo.toml
  cli/src/print.rs
Labels: enhancement

#832 Improvement `validate_unique` function when only `PrimaryKey` exists
  core/src/executor/execute.rs
  core/src/executor/validate.rs
  test-suite/src/primary_key.rs
Labels: improvement

#833 [Function] Implement `TO_DATE` and `TO_TIMESTAMP` function
  core/src/ast/function.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/to_date.rs
  test-suite/src/lib.rs
Labels: enhancement

#802 [AST builder] Implement Insert statement
  core/src/ast_builder/column_list.rs
  core/src/ast_builder/insert.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/table.rs
  core/src/parse_sql.rs
  core/src/translate/mod.rs
Labels: enhancement

#836 [AST Builder] Implement format function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#840 Update core/ chrono dependency version to 0.4.22, specify patch version
  core/Cargo.toml
Labels: bug

#838 [AST builder] Implement To_date and To_timestamp function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#841 Implement order by ast builder
  core/src/ast_builder/mod.rs
  core/src/ast_builder/order_by_expr.rs
  core/src/ast_builder/order_by_expr_list.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/having.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
  core/src/parse_sql.rs
Labels: enhancement

#842 [Function] Implement `TO_TIME` function and let `FORMAT` get `TIME` data type
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/format.rs
  test-suite/src/function/to_date.rs
Labels: enhancement

#846 [Data] modify int8 to parse sql int(8) format to int8
  core/src/data/key.rs
  core/src/translate/data_type.rs
  test-suite/src/data_type/int8.rs
  test-suite/src/function/abs.rs
  test-suite/src/function/cast.rs
  test-suite/src/function/ifnull.rs
  test-suite/src/showcolumns.rs
  test-suite/src/unary_operator.rs
Labels: improvement

#847 [Data] modify int16 to parse sql int(16) format to int16
  core/src/data/key.rs
  core/src/translate/data_type.rs
  test-suite/src/data_type/int16.rs
Labels: improvement

#848 [Data] modify int32 to parse sql int(32) format to int32
  core/src/data/key.rs
  core/src/translate/data_type.rs
  test-suite/src/data_type/int32.rs
Labels: improvement

#850 [Data] modify int128 to parse sql int(128) format to int128
  core/src/translate/data_type.rs
  test-suite/src/data_type/int128.rs
Labels: improvement

#851 [Data] modify uint8 to parse sql 'INT(8) UNSIGNED' format to 'UINT8'
  core/src/data/key.rs
  core/src/translate/data_type.rs
  test-suite/src/data_type/uint8.rs
  test-suite/src/function/cast.rs
Labels: improvement

#852 docs(readme): update readme
  README.md
Labels: documentation

#812 [AST] Implement to_sql func for OrderByExpr
  core/src/ast/mod.rs
  core/src/ast/query.rs
Labels: enhancement

#858 [AST Builder] Implement to_date and let format function to format date data type
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#820 Support CLI options
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/print.rs
Labels: enhancement

#803 [Ast Builder] Implement join expression in select statement
  core/src/ast_builder/mod.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/filter.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/having.rs
  core/src/ast_builder/select/join.rs
  core/src/ast_builder/select/join_constraint.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/limit_offset.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
Labels: enhancement

#872 Update test-suite Tester trait to use Glue struct
  gluesql-js/web/tests/memory_storage.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/shared-memory-storage/tests/shared_memory_storage.rs
  storages/sled-storage/tests/sled_storage.rs
  test-suite/src/tester/mod.rs
Labels: improvement

#871 Support `.edit {fileName|None}` in CLI
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/print.rs
Labels: enhancement

#873 refactor: Replace `ObjectName` with `String`
  core/src/ast/ddl.rs
  core/src/ast/expr.rs
  core/src/ast/mod.rs
  core/src/ast/query.rs
  core/src/ast_builder/alter_table.rs
  core/src/ast_builder/create_table.rs
  core/src/ast_builder/delete.rs
  core/src/ast_builder/drop_table.rs
  core/src/ast_builder/index.rs
  core/src/ast_builder/insert.rs
  core/src/ast_builder/select/join.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/show_columns.rs
  core/src/ast_builder/update.rs
  core/src/data/mod.rs
  core/src/data/table.rs
  core/src/executor/alter/alter_table.rs
  core/src/executor/alter/index.rs
  core/src/executor/alter/mod.rs
  core/src/executor/alter/table.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/select/blend.rs
  core/src/executor/select/mod.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/planner.rs
  core/src/plan/primary_key.rs
  core/src/plan/schema.rs
  core/src/translate/ddl.rs
  core/src/translate/error.rs
  core/src/translate/function.rs
  core/src/translate/mod.rs
  core/src/translate/query.rs
  test-suite/src/basic.rs
Labels: improvement

#878 refactor: remove redundant TableFactor::Series.name
  core/src/ast/query.rs
  core/src/data/table.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/planner.rs
  core/src/translate/query.rs
Labels: improvement
