Repository gluesql/gluesql, pull requests merged in 2022-01, with the labels that each got.

#446 Convert `gluesql` workspace to root lib-package
  .github/workflows/rust.yml
  .gitignore
  Cargo.toml
  cli/Cargo.toml
  core/Cargo.toml
  examples/api_usage.rs
  examples/hello_world.rs
  examples/sled_multi_threaded.rs
  examples/using_config.rs
  gluesql/Cargo.toml
  gluesql/examples/api_usage.rs
  gluesql/examples/using_config.rs
  src/lib.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/tests/memory_storage.rs
  storages/sled-storage/Cargo.toml
  storages/sled-storage/tests/sled_storage.rs
  storages/sled-storage/tests/sled_transaction.rs
  test-suite/Cargo.toml
  tests/glue.rs
  utils/Cargo.toml
Labels: enhancement

#447 Fill in the missing #446
  storages/sled-storage/Cargo.toml
  tests/glue.rs
  utils/Cargo.toml
Labels: bug

#450 Remove sorter cfg feature, support all ORDER BY by default
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  cli/Cargo.toml
  core/Cargo.toml
  core/src/executor/select/error.rs
  core/src/executor/select/mod.rs
  storages/memory-storage/Cargo.toml
  storages/sled-storage/Cargo.toml
  test-suite/Cargo.toml
  test-suite/src/index/mod.rs
  test-suite/src/index/order_by.rs
  test-suite/src/lib.rs
  test-suite/src/limit.rs
  test-suite/src/order_by.rs
Labels: improvement

#453 Apply Serde to MemoryStorage instance and make it public,
  storages/memory-storage/Cargo.toml
  storages/memory-storage/src/lib.rs
Labels: improvement

#451 Add [[bin]] to Cargo.toml, update cli and storage workspace versions,
  cli/Cargo.toml
  cli/src/main.rs
  core/Cargo.toml
  test-suite/src/metadata.rs
Labels: improvement

#459 Remove duplicate action
  .github/release-drafter-config.yml
  .github/workflows/coverage.yml
  .github/workflows/mdbook.yml
Labels: improvement

#456 Prepare v0.10.0 release
  Cargo.toml
  README.md
  cli/Cargo.toml
  core/Cargo.toml
  src/lib.rs
  test-suite/src/tester.rs
Labels: documentation, improvement

#461 Prepare cargo publish
  Cargo.toml
  cli/Cargo.toml
  cli/src/main.rs
  core/Cargo.toml
  src/lib.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/tests/memory_storage.rs
  storages/sled-storage/Cargo.toml
  storages/sled-storage/benches/sled_benchmark.rs
  storages/sled-storage/tests/sled_storage.rs
  storages/sled-storage/tests/sled_transaction.rs
  test-suite/Cargo.toml
  tests/glue.rs
  utils/Cargo.toml
Labels: documentation, improvement

#465 Remove gluesql prefix in dependencies and features
  Cargo.toml
  core/Cargo.toml
  core/src/executor/aggregate/state.rs
  core/src/executor/join.rs
  core/src/executor/sort.rs
  core/src/executor/validate.rs
  core/src/plan.rs
  src/lib.rs
  src/main.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/tests/memory_storage.rs
  storages/sled-storage/Cargo.toml
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index.rs
  storages/sled-storage/src/index_sync.rs
  storages/sled-storage/tests/sled_storage.rs
  storages/sled-storage/tests/sled_transaction.rs
  tests/glue.rs
Labels: improvement

#466 Support `limit`, `offset` clause in `Insert into Table Select ~`
  core/src/executor/execute.rs
  test-suite/src/limit.rs
Labels: improvement

#467 Add --all-targets to cargo test in github rust action
  .github/workflows/rust.yml
Labels: improvement

#469 Fix src/lib.rs doc comment,
  src/lib.rs
Labels: bug

#471 Update evaluate_stateless to support all existing SQL functions,
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  test-suite/src/data_type/map.rs
  test-suite/src/default.rs
  test-suite/src/function/ceil.rs
  test-suite/src/function/degrees.rs
  test-suite/src/function/div_mod.rs
  test-suite/src/function/exp_log.rs
  test-suite/src/function/floor.rs
  test-suite/src/function/gcd_lcm.rs
  test-suite/src/function/generate_uuid.rs
  test-suite/src/function/left_right.rs
  test-suite/src/function/lpad_rpad.rs
  test-suite/src/function/ltrim_rtrim.rs
  test-suite/src/function/math_function.rs
  test-suite/src/function/now.rs
  test-suite/src/function/pi.rs
  test-suite/src/function/radians.rs
  test-suite/src/function/repeat.rs
  test-suite/src/function/reverse.rs
  test-suite/src/function/round.rs
  test-suite/src/function/sqrt_power.rs
  test-suite/src/function/substr.rs
  test-suite/src/function/trim.rs
  test-suite/src/function/upper_lower.rs
Labels: improvement

#472 Update Join::apply to take the whole table(rows) as a stream iterator
  core/src/executor/join.rs
  core/src/executor/select/mod.rs
Labels: improvement
