Repository gluesql/gluesql, pull requests merged in 2022-07, with the labels that each got.

#613 Implement query builder base (AST builder)
  core/src/ast_builder/delete.rs
  core/src/ast_builder/expr/aggregate.rs
  core/src/ast_builder/expr/binary_op.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/is_null.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/expr/nested.rs
  core/src/ast_builder/expr_list.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/having.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/limit_offset.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/select_item_list.rs
  core/src/ast_builder/table.rs
  core/src/lib.rs
  core/src/parse_sql.rs
  core/src/translate/mod.rs
  core/src/translate/query.rs
Labels: enhancement

#622 Remove unnecessary `Result`
  core/src/executor/aggregate/mod.rs
Labels: improvement

#616 Add floor func in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#620 feat(ast_build): implement ifnull function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#523 Support Inline view (FROM clause subquery)
  core/src/ast/query.rs
  core/src/data/mod.rs
  core/src/data/table.rs
  core/src/executor/aggregate/mod.rs
  core/src/executor/alter/table.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/join.rs
  core/src/executor/select/blend.rs
  core/src/executor/select/mod.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/schema.rs
  core/src/translate/error.rs
  core/src/translate/query.rs
  test-suite/src/error.rs
  test-suite/src/inline_view.rs
  test-suite/src/lib.rs
  test-suite/src/migrate.rs
Labels: enhancement

#626 implement ast_builder/expr/function/{Left, Right}
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#621 feat(ast_build): implement upper function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#627 Implements trigonometric functions in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#637 Implement add reverse func in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#635 feat(ast_builder): Add Agggregate functions
  core/src/ast_builder/expr/aggregate.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#645 implement ceil function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#647 Update coverage action to use grcov & Coveralls
  .github/workflows/coverage.yml
  README.md
Labels: improvement

#649 Add missing test case in `test-suite` workspace
  test-suite/src/lib.rs
  test-suite/src/transaction/alter_table.rs
Labels: improvement

#650 Implement AST-builder log2, log10 function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#653 Enhance SelectNode::filter
  core/src/ast_builder/expr/binary_op.rs
  core/src/ast_builder/select/root.rs
Labels: enhancement

#654 Implement ast_builder binary::gte&lte&or
  core/src/ast_builder/expr/binary_op.rs
Labels: enhancement

#655 Add more expression support to project,
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select_item.rs
  core/src/ast_builder/select_item_list.rs
  core/src/parse_sql.rs
Labels: enhancement

#656 [AST Builder] Implement Agggregate function `COUNT`
  core/src/ast_builder/expr/aggregate.rs
  core/src/ast_builder/mod.rs
  core/src/translate/function.rs
Labels: enhancement, improvement

#657 Implement round function in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#666 Implement AST-builder extract functions
  core/src/ast_builder/expr/extract.rs
  core/src/ast_builder/expr/mod.rs
Labels: enhancement

#669 Implement unary_op (+, -, NOT, !) in ast_builder
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/expr/unary_op.rs
Labels: enhancement

#675 [Data] Add function `sqrt` for enum `Value`
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  test-suite/src/function/sqrt_power.rs
Labels: enhancement

#681 refactor(ast_build): reorder binary_op functions and tests
  core/src/ast_builder/expr/binary_op.rs
Labels: improvement

#680 Implement `ln` in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#682 Convert `TryInto` traits into `TryFrom`
  core/src/data/value/convert.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/evaluated.rs
Labels: improvement

#686 feat(ast_build): implement binary operations (modulo, like, ilike. not_like, not_ilike)
  core/src/ast_builder/expr/binary_op.rs
Labels: enhancement

#672 Implement AST-builder between expression function
  core/src/ast_builder/expr/between.rs
  core/src/ast_builder/expr/mod.rs
Labels: enhancement

#689 [AST Builder] Implement show_columns Expr
  core/src/ast_builder/mod.rs
  core/src/ast_builder/show_columns.rs
  core/src/ast_builder/table.rs
Labels: enhancement

#684 Add `STDEV` aggregate funtion
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast_builder/expr/aggregate.rs
  core/src/ast_builder/mod.rs
  core/src/executor/aggregate/state.rs
  core/src/plan/expr/aggregate.rs
  core/src/translate/function.rs
  test-suite/src/aggregate.rs
Labels: enhancement

#692 implement now function in ast builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#695 [AST Builder] Implement drop_table Expr
  core/src/ast_builder/drop_table.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/table.rs
Labels: enhancement

#659 Enhance `Values List` to validate column type
  core/src/data/value/mod.rs
  core/src/executor/select/mod.rs
  test-suite/src/values.rs
Labels: enhancement

#699 Run github action job parallel
  .github/workflows/rust.yml
Labels: improvement
