Repository gluesql/gluesql, pull requests merged in 2022-12, with the labels that each got.

#1026 Update `data::Row` to contain columns
  cli/src/lib.rs
  cli/src/print.rs
  core/src/data/row.rs
  core/src/executor/alter/table.rs
  core/src/executor/context/blend_context.rs
  core/src/executor/context/filter_context.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/join.rs
  core/src/executor/mod.rs
  core/src/executor/select/blend.rs
  core/src/executor/select/error.rs
  core/src/executor/select/mod.rs
  core/src/executor/sort.rs
  core/src/executor/update.rs
  core/src/executor/validate.rs
  core/src/lib.rs
  core/src/plan/mock.rs
  core/src/result.rs
  core/src/store/mod.rs
  pkg/rust/tests/glue.rs
  storages/memory-storage/src/alter_table.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/src/lib.rs
  storages/shared-memory-storage/tests/concurrent_access.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/gc.rs
  storages/sled-storage/src/index.rs
  storages/sled-storage/src/index_sync.rs
  storages/sled-storage/src/store.rs
  storages/sled-storage/src/store_mut.rs
  storages/sled-storage/src/transaction.rs
  test-suite/src/blend.rs
  test-suite/src/tester/macros.rs
Labels: improvement

#1029 Merge FilterContext and BlendContext into RowContext
  core/src/executor/aggregate/mod.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/context/aggregate_context.rs
  core/src/executor/context/blend_context.rs
  core/src/executor/context/filter_context.rs
  core/src/executor/context/mod.rs
  core/src/executor/context/row_context.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/fetch.rs
  core/src/executor/filter.rs
  core/src/executor/join.rs
  core/src/executor/select/blend.rs
  core/src/executor/select/mod.rs
  core/src/executor/sort.rs
  core/src/executor/update.rs
  test-suite/src/aggregate/group_by.rs
Labels: improvement

#1031 Merge insert logics in row.rs & execute.rs into executor/insert.rs
  core/src/data/row.rs
  core/src/executor/execute.rs
  core/src/executor/insert.rs
  core/src/executor/mod.rs
  core/src/result.rs
  test-suite/src/values.rs
Labels: improvement

#1028 Fix test-suite tester functions to show (found, expected) shape
  test-suite/src/tester/mod.rs
Labels: bug

#1032 Remove `Content::Shared` variant in executor/ `RowContext`
  core/src/executor/context/row_context.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/fetch.rs
  core/src/executor/join.rs
  core/src/executor/select/mod.rs
  core/src/executor/sort.rs
  core/src/executor/update.rs
Labels: improvement

#1022 Add Debug to AST builder nodes
  core/src/ast_builder/alter_table.rs
  core/src/ast_builder/assignment.rs
  core/src/ast_builder/column_def.rs
  core/src/ast_builder/column_list.rs
  core/src/ast_builder/create_table.rs
  core/src/ast_builder/data_type.rs
  core/src/ast_builder/delete.rs
  core/src/ast_builder/drop_table.rs
  core/src/ast_builder/expr/aggregate.rs
  core/src/ast_builder/expr/case.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/in_list.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/expr/numeric.rs
  core/src/ast_builder/expr_list.rs
  core/src/ast_builder/index.rs
  core/src/ast_builder/insert.rs
  core/src/ast_builder/order_by_expr.rs
  core/src/ast_builder/order_by_expr_list.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/filter.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/having.rs
  core/src/ast_builder/select/join/hash_join.rs
  core/src/ast_builder/select/join/join_constraint.rs
  core/src/ast_builder/select/join/mod.rs
  core/src/ast_builder/select/join/root.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/limit_offset.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/select_item.rs
  core/src/ast_builder/select_item_list.rs
  core/src/ast_builder/show_columns.rs
  core/src/ast_builder/table_factor.rs
  core/src/ast_builder/table_name.rs
  core/src/ast_builder/update.rs
Labels: improvement

#1039 Reorder project in ASTBuilder (project -> ordery_by -> limit,offset)
  core/src/ast_builder/insert.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  test-suite/src/ast_builder/select.rs
Labels: improvement

#1043 [AST-Builder] Remove unused prebuild nodes
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
Labels: improvement

#1042 Move ast::ColumnOption::Default variant to ColumnDef
  core/src/ast/ddl.rs
  core/src/ast/mod.rs
  core/src/data/schema.rs
  core/src/executor/alter/table.rs
  core/src/executor/alter/validate.rs
  core/src/executor/insert.rs
  core/src/executor/validate.rs
  core/src/plan/mock.rs
  core/src/translate/ddl.rs
  storages/memory-storage/src/alter_table.rs
  storages/sled-storage/src/alter_table.rs
  test-suite/src/alter/alter_table.rs
Labels: improvement

#1045 Rewrite & simplify plan/context.rs codes,
  core/src/plan/context.rs
  core/src/plan/evaluable.rs
  core/src/plan/join.rs
  core/src/plan/planner.rs
  core/src/plan/primary_key.rs
Labels: improvement

#1044 Remove ast::ColumnOption and merge UNIQUE option to ColumnDef
  core/src/ast/ddl.rs
  core/src/ast/mod.rs
  core/src/data/schema.rs
  core/src/executor/alter/table.rs
  core/src/executor/alter/validate.rs
  core/src/executor/fetch.rs
  core/src/executor/insert.rs
  core/src/executor/update.rs
  core/src/executor/validate.rs
  core/src/plan/mock.rs
  core/src/plan/planner.rs
  core/src/translate/ddl.rs
  storages/sled-storage/src/alter_table.rs
  test-suite/src/alter/alter_table.rs
Labels: improvement

#1049 Update js/ Cargo.toml to use gloo-utils for serde handling
  pkg/javascript/web/Cargo.toml
  pkg/javascript/web/src/payload.rs
  pkg/javascript/web/tests/payload.rs
Labels: improvement

#1046 Schemaless data support
  cli/src/lib.rs
  cli/src/print.rs
  cli/tests/dump.rs
  core/src/ast/mod.rs
  core/src/data/mod.rs
  core/src/data/row.rs
  core/src/data/schema.rs
  core/src/data/value/json.rs
  core/src/data/value/mod.rs
  core/src/executor/alter/index.rs
  core/src/executor/alter/table.rs
  core/src/executor/context/row_context.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/insert.rs
  core/src/executor/join.rs
  core/src/executor/select/mod.rs
  core/src/executor/select/project.rs
  core/src/executor/sort.rs
  core/src/executor/update.rs
  core/src/executor/validate.rs
  core/src/plan/mock.rs
  core/src/plan/planner.rs
  core/src/plan/validate.rs
  core/src/result.rs
  core/src/store/alter_table.rs
  core/src/store/data_row.rs
  core/src/store/mod.rs
  pkg/javascript/web/src/payload.rs
  pkg/javascript/web/tests/payload.rs
  storages/memory-storage/src/alter_table.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/src/lib.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/gc.rs
  storages/sled-storage/src/index.rs
  storages/sled-storage/src/index_sync.rs
  storages/sled-storage/src/store.rs
  storages/sled-storage/src/store_mut.rs
  storages/sled-storage/src/transaction.rs
  test-suite/Cargo.toml
  test-suite/src/lib.rs
  test-suite/src/schemaless/basic.rs
  test-suite/src/schemaless/error.rs
  test-suite/src/schemaless/mod.rs
  test-suite/src/tester/macros.rs
  utils/src/hashmap.rs
  utils/src/lib.rs
Labels: enhancement

#1050 Add WebStorage - support localStorage & sessionStorage for web browsers
  .github/workflows/rust.yml
  storages/web-storage/Cargo.toml
  storages/web-storage/README.md
  storages/web-storage/src/lib.rs
  storages/web-storage/tests/local_storage.rs
  storages/web-storage/tests/session_storage.rs
Labels: enhancement
