Repository gluesql/gluesql, pull requests merged in 2022-08, with the labels that each got.

#702 Mark flaky test using target_os cfg
  storages/sled-storage/tests/sled_transaction.rs
Labels: improvement

#706 Add DROP TABLE multi object test case in integration test
  test-suite/src/alter/drop_table.rs
Labels: improvement

#673 [AST Builder] Implement Index Expr
  core/src/ast_builder/index.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/order_by_expr.rs
  core/src/ast_builder/table.rs
  core/src/parse_sql.rs
Labels: enhancement

#697 [AST Builder] Implement AST builder InList function
  core/src/ast_builder/expr/in_list.rs
  core/src/ast_builder/expr/mod.rs
Labels: enhancement

#709 [AST Builder] Implement Transaction Statements
  core/src/ast_builder/mod.rs
  core/src/ast_builder/transaction.rs
Labels: enhancement

#711 [AST Builder] Implement Sign function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#715 Remove clippy warning in mac os
  storages/sled-storage/tests/sled_transaction.rs
Labels: improvement

#716 Remove unnecessary `Box`
  core/src/ast/mod.rs
  core/src/ast_builder/select/mod.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/translate/mod.rs
Labels: improvement

#721 [AST Builder] Implement InSubquery and QueryNode
  core/src/ast_builder/expr/in_subquery.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/query.rs
Labels: enhancement

#722 import only where you use `Duration`
  storages/sled-storage/tests/sled_transaction.rs
Labels: improvement

#723 [AST Builder] Update FunctionNode structure
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/mod.rs
Labels: improvement

#726 feat:[#725] Implement `Power` and `Sqrt` function to `ast_builder`
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#729 feat:[#728] Implement `Log`function to `ast_builder`
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#736 Support `.columns TABLE` command in CLI
  cli/Cargo.toml
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/print.rs
Labels: enhancement

#734 feat:[#732] Implement `Gcd` and `Lcm` function to `ast_builder`
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#738 Add Update integration test
  test-suite/src/error.rs
  test-suite/src/lib.rs
  test-suite/src/update.rs
Labels: improvement

#740 [AST Builder] Implement GenerateUuid Funciton
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#742 [AST Builder] Implement Repeat Funciton
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#755 [AST Builder] Implement radians, degrees Funciton
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#750 [AST Builder] Implement Concat Funciton
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#759 Implement cast function in AST builder
  core/src/ast_builder/data_type.rs
  core/src/ast_builder/expr/cast.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
  core/src/parse_sql.rs
  core/src/translate/mod.rs
Labels: enhancement

#748 Support `.spool FilePath` command in CLI
  cli/src/cli.rs
  cli/src/command.rs
  cli/src/print.rs
Labels: enhancement

#704 Support CTAV(Create Table As Values)
  core/src/executor/alter/table.rs
  core/src/result.rs
  test-suite/src/values.rs
Labels: enhancement

#687 Implement primary key support,
  core/src/ast/query.rs
  core/src/data/mod.rs
  core/src/data/table.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/update.rs
  core/src/plan/context.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/mock.rs
  core/src/plan/mod.rs
  core/src/plan/planner.rs
  core/src/plan/primary_key.rs
  core/src/store/mod.rs
  core/src/translate/ddl.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/src/lib.rs
  storages/sled-storage/src/store.rs
  test-suite/src/alter/create_table.rs
  test-suite/src/basic.rs
  test-suite/src/lib.rs
  test-suite/src/macros.rs
  test-suite/src/primary_key.rs
Labels: enhancement

#752 [AST Builder] Implement Lpad, Rpad Funciton
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#758 [AST Builder] Implement substr Funciton
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#770 Update `Expr::CompoundIdentifier` to have more accurate data format
  core/src/ast/expr.rs
  core/src/ast_builder/expr/mod.rs
  core/src/executor/aggregate/error.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/evaluable.rs
  core/src/plan/expr/mod.rs
  core/src/plan/planner.rs
  core/src/plan/primary_key.rs
  core/src/plan/schema.rs
  core/src/translate/expr.rs
  test-suite/src/aggregate.rs
  test-suite/src/migrate.rs
Labels: improvement

#771 [Test Suite] Refactor `aggregate`
  test-suite/src/aggregate.rs
  test-suite/src/aggregate/avg.rs
  test-suite/src/aggregate/count.rs
  test-suite/src/aggregate/error.rs
  test-suite/src/aggregate/group_by.rs
  test-suite/src/aggregate/max.rs
  test-suite/src/aggregate/min.rs
  test-suite/src/aggregate/mod.rs
  test-suite/src/aggregate/stdev.rs
  test-suite/src/aggregate/sum.rs
  test-suite/src/aggregate/variance.rs
  test-suite/src/lib.rs
Labels: improvement

#773 [Test Suite] Refactor `arithmetic`
  test-suite/src/arithmetic/blend.rs
  test-suite/src/arithmetic/error.rs
  test-suite/src/arithmetic/mod.rs
  test-suite/src/arithmetic/on_where.rs
  test-suite/src/lib.rs
Labels: improvement

#763 feat:[#756] implement Ltrim and Rtrim function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#777 Add QueryNode enum and test_query function
  core/src/ast_builder/mod.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/mod.rs
Labels: enhancement

#731 Support `Derived VALUES`
  core/src/executor/fetch.rs
  test-suite/src/values.rs
Labels: enhancement

#775 [Test Suite] delete unneccesary keyword `vec!`, `iter()`
  test-suite/src/aggregate/avg.rs
  test-suite/src/aggregate/count.rs
  test-suite/src/aggregate/error.rs
  test-suite/src/aggregate/group_by.rs
  test-suite/src/aggregate/max.rs
  test-suite/src/aggregate/min.rs
  test-suite/src/aggregate/stdev.rs
  test-suite/src/aggregate/sum.rs
  test-suite/src/aggregate/variance.rs
  test-suite/src/alter/alter_table.rs
  test-suite/src/alter/create_table.rs
  test-suite/src/alter/drop_table.rs
  test-suite/src/arithmetic/on_where.rs
  test-suite/src/blend.rs
  test-suite/src/case.rs
  test-suite/src/data_type/bytea.rs
  test-suite/src/data_type/decimal.rs
  test-suite/src/data_type/sql_types.rs
  test-suite/src/data_type/uuid.rs
  test-suite/src/default.rs
  test-suite/src/error.rs
  test-suite/src/filter.rs
  test-suite/src/function/abs.rs
  test-suite/src/function/cast.rs
  test-suite/src/function/ceil.rs
  test-suite/src/function/degrees.rs
  test-suite/src/function/div_mod.rs
  test-suite/src/function/exp_log.rs
  test-suite/src/function/extract.rs
  test-suite/src/function/floor.rs
  test-suite/src/function/gcd_lcm.rs
  test-suite/src/function/generate_uuid.rs
  test-suite/src/function/ifnull.rs
  test-suite/src/function/left_right.rs
  test-suite/src/function/lpad_rpad.rs
  test-suite/src/function/ltrim_rtrim.rs
  test-suite/src/function/math_function.rs
  test-suite/src/function/now.rs
  test-suite/src/function/pi.rs
  test-suite/src/function/radians.rs
  test-suite/src/function/repeat.rs
  test-suite/src/function/reverse.rs
  test-suite/src/function/round.rs
  test-suite/src/function/sign.rs
  test-suite/src/function/sqrt_power.rs
  test-suite/src/function/substr.rs
  test-suite/src/function/trim.rs
  test-suite/src/function/upper_lower.rs
  test-suite/src/inline_view.rs
  test-suite/src/join.rs
  test-suite/src/limit.rs
  test-suite/src/migrate.rs
  test-suite/src/nested_select.rs
  test-suite/src/nullable.rs
  test-suite/src/ordering.rs
  test-suite/src/synthesize.rs
  test-suite/src/unary_operator.rs
  test-suite/src/update.rs
  test-suite/src/validate/types.rs
  test-suite/src/validate/unique.rs
Labels: improvement

#788 [Test Suite] Merge use crates into one
  test-suite/src/alter/alter_table.rs
  test-suite/src/alter/create_table.rs
  test-suite/src/alter/drop_table.rs
  test-suite/src/blend.rs
  test-suite/src/case.rs
  test-suite/src/concat.rs
  test-suite/src/data_type/date.rs
  test-suite/src/data_type/interval.rs
  test-suite/src/data_type/time.rs
  test-suite/src/data_type/timestamp.rs
  test-suite/src/default.rs
  test-suite/src/error.rs
  test-suite/src/filter.rs
  test-suite/src/function/abs.rs
  test-suite/src/function/cast.rs
  test-suite/src/function/ceil.rs
  test-suite/src/function/concat.rs
  test-suite/src/function/degrees.rs
  test-suite/src/function/div_mod.rs
  test-suite/src/function/exp_log.rs
  test-suite/src/function/floor.rs
  test-suite/src/function/gcd_lcm.rs
  test-suite/src/function/generate_uuid.rs
  test-suite/src/function/ifnull.rs
  test-suite/src/function/left_right.rs
  test-suite/src/function/lpad_rpad.rs
  test-suite/src/function/ltrim_rtrim.rs
  test-suite/src/function/math_function.rs
  test-suite/src/function/pi.rs
  test-suite/src/function/radians.rs
  test-suite/src/function/repeat.rs
  test-suite/src/function/reverse.rs
  test-suite/src/function/round.rs
  test-suite/src/function/sign.rs
  test-suite/src/function/sqrt_power.rs
  test-suite/src/function/substr.rs
  test-suite/src/function/trim.rs
  test-suite/src/function/upper_lower.rs
  test-suite/src/index/and.rs
  test-suite/src/index/basic.rs
  test-suite/src/index/expr.rs
  test-suite/src/index/nested.rs
  test-suite/src/index/null.rs
  test-suite/src/index/order_by.rs
  test-suite/src/index/showindexes.rs
  test-suite/src/index/value.rs
  test-suite/src/join.rs
  test-suite/src/limit.rs
  test-suite/src/migrate.rs
  test-suite/src/order_by.rs
  test-suite/src/showcolumns.rs
  test-suite/src/synthesize.rs
  test-suite/src/transaction/basic.rs
  test-suite/src/unary_operator.rs
  test-suite/src/update.rs
  test-suite/src/validate/types.rs
  test-suite/src/validate/unique.rs
Labels: improvement

#733 Support `SELECT * FROM SERIES(N)` and `SELECT 1`(without table)
  core/src/ast/query.rs
  core/src/data/table.rs
  core/src/executor/alter/table.rs
  core/src/executor/fetch.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/planner.rs
  core/src/plan/schema.rs
  core/src/translate/error.rs
  core/src/translate/function.rs
  core/src/translate/query.rs
  test-suite/src/error.rs
  test-suite/src/lib.rs
  test-suite/src/series.rs
Labels: enhancement

#792 [Test Suite] move `top level test files` to `new tester folder`
  test-suite/src/lib.rs
  test-suite/src/tester/macros.rs
  test-suite/src/tester/mod.rs
Labels: improvement

#760 [AST Builder] Implement Div, Mod Function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#795 Impl `TryFrom<&Value> for usize`
  core/src/data/value/convert.rs
  core/src/executor/limit.rs
Labels: improvement

#720 [AST Builder] Implement update Expression
  core/src/ast_builder/assignment.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/table.rs
  core/src/ast_builder/update.rs
  core/src/parse_sql.rs
  core/src/translate/mod.rs
Labels: enhancement

#794 [Test Suite] rearrange `error test cases` to `correct file`
  test-suite/src/alter/alter_table.rs
  test-suite/src/alter/drop_indexed.rs
  test-suite/src/blend.rs
  test-suite/src/case.rs
  test-suite/src/error.rs
  test-suite/src/function/extract.rs
  test-suite/src/join.rs
  test-suite/src/lib.rs
  test-suite/src/migrate.rs
  test-suite/src/nested_select.rs
  test-suite/src/values.rs
Labels: improvement

#797 Small improvement: add clear guide for web example module
  gluesql-js/examples/web/module/README.md
  gluesql-js/index.html
Labels: documentation

#800 [AST-Builder] change error message in test functions
  core/src/ast_builder/assignment.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/order_by_expr.rs
  core/src/ast_builder/select_item.rs
  core/src/ast_builder/select_item_list.rs
Labels: improvement

#790 [AST Builder] Implement EXISTS Expression
  core/src/ast_builder/expr/exists.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#749 Update aggregate functions to support `Expr`
  core/src/executor/aggregate/error.rs
  core/src/executor/aggregate/mod.rs
  core/src/executor/aggregate/state.rs
  test-suite/src/aggregate/error.rs
  test-suite/src/aggregate/max.rs
  test-suite/src/aggregate/min.rs
  test-suite/src/aggregate/sum.rs
Labels: enhancement
