Repository gluesql/gluesql, pull requests merged in 2022-04, with the labels that each got.

#507 Minor improvements
  core/src/glue.rs
  core/src/parse_sql.rs
Labels: improvement

#519 Fix CLI --execute {file}.sql option to support CRLF line break,
  cli/src/cli.rs
Labels: bug

#518 Add unit tests to data/value/into.rs module
  core/src/data/value/into.rs
Labels: improvement

#510 add ABS and SIGN functions
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/abs.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/sign.rs
  test-suite/src/lib.rs
Labels: enhancement

#517 Show columns take2
  cli/src/print.rs
  core/src/ast/data_type.rs
  core/src/ast/mod.rs
  core/src/executor/execute.rs
  core/src/lib.rs
  core/src/translate/mod.rs
  test-suite/src/lib.rs
  test-suite/src/showcolumns.rs
Labels: enhancement

#534 resolve issue #424
  core/src/data/mod.rs
  core/src/data/value/binary_op/f64.rs
  core/src/data/value/binary_op/i64.rs
  core/src/data/value/binary_op/i8.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  test-suite/src/arithmetic.rs
Labels: improvement

#537 Scalar subquery should throw Error when more than one row returned
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/mod.rs
  test-suite/src/error.rs
  test-suite/src/ordering.rs
Labels: improvement

#521 Concat function implementation
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/error.rs
  core/src/translate/function.rs
  test-suite/src/function/concat.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#541 Migrate sqlparser-rs version from v0.13 to v0.14,
  core/Cargo.toml
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast/mod.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/aggregate.rs
  core/src/plan/expr/mod.rs
  core/src/plan/join.rs
  core/src/translate/error.rs
  core/src/translate/expr.rs
  core/src/translate/function.rs
  test-suite/src/aggregate.rs
Labels: improvement
