Repository gluesql/gluesql, pull requests merged in 2022-10, with the labels that each got.

#884 Auto Implement `GStore`, `GStoreMut` traits
  core/src/plan/mock.rs
  core/src/store/mod.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/src/lib.rs
  storages/sled-storage/src/lib.rs
Labels: improvement

#885 Add root workspace in members
  .github/workflows/rust.yml
  Cargo.toml
Labels: improvement

#879 Implement AST builder execute function
  core/src/ast_builder/alter_table.rs
  core/src/ast_builder/build.rs
  core/src/ast_builder/create_table.rs
  core/src/ast_builder/delete.rs
  core/src/ast_builder/drop_table.rs
  core/src/ast_builder/execute.rs
  core/src/ast_builder/expr/exists.rs
  core/src/ast_builder/index.rs
  core/src/ast_builder/insert.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/filter.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/having.rs
  core/src/ast_builder/select/join.rs
  core/src/ast_builder/select/join_constraint.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/limit_offset.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/show_columns.rs
  core/src/ast_builder/update.rs
  test-suite/src/ast_builder/basic.rs
  test-suite/src/ast_builder/mod.rs
  test-suite/src/lib.rs
  test-suite/src/tester/mod.rs
  tests/glue.rs
Labels: enhancement

#875 Implement str_position function under enum Value
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
Labels: enhancement

#869 Support Dictionary(Schema) view
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  cli/Cargo.toml
  core/Cargo.toml
  core/src/ast/mod.rs
  core/src/ast/query.rs
  core/src/data/table.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/mod.rs
  core/src/lib.rs
  core/src/plan/evaluable.rs
  core/src/plan/index.rs
  core/src/plan/mock.rs
  core/src/plan/planner.rs
  core/src/plan/schema.rs
  core/src/store/metadata.rs
  core/src/store/mod.rs
  core/src/translate/mod.rs
  core/src/translate/query.rs
  gluesql-js/web/Cargo.toml
  gluesql-js/web/tests/memory_storage.rs
  gluesql-js/web/tests/payload.rs
  src/lib.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/src/lib.rs
  storages/memory-storage/src/metadata.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/shared-memory-storage/Cargo.toml
  storages/shared-memory-storage/src/lib.rs
  storages/shared-memory-storage/src/metadata.rs
  storages/shared-memory-storage/tests/shared_memory_storage.rs
  storages/sled-storage/Cargo.toml
  storages/sled-storage/src/lib.rs
  storages/sled-storage/src/metadata.rs
  storages/sled-storage/src/store.rs
  storages/sled-storage/tests/sled_storage.rs
  storages/sled-storage/tests/sled_transaction.rs
  test-suite/Cargo.toml
  test-suite/src/dictionary.rs
  test-suite/src/lib.rs
  test-suite/src/metadata.rs
  test-suite/src/transaction/dictionary.rs
  test-suite/src/transaction/mod.rs
Labels: enhancement

#888 Set default-run to root workspace Cargo.toml
  Cargo.toml
Labels: bug

#889 Update README.md; add `await` keyword.
  gluesql-js/README.md
Labels: documentation

#891 Remove comment
  core/src/result.rs
Labels: improvement

#892 Use variable instead of closure in core/ evaluate function module
  core/src/executor/evaluate/mod.rs
Labels: improvement

#860 [AST] Implement to_sql func for Query, SetExpr, Select, SelectItem, TableWithJoins, IndexItem, TableFactor, TableAlias
  core/src/ast/expr.rs
  core/src/ast/query.rs
  examples/query_parser.rs
Labels: enhancement

#900 Enable str to string clippy options
  cli/src/command.rs
  cli/src/lib.rs
  cli/src/print.rs
  core/src/ast/ast_literal.rs
  core/src/ast/ddl.rs
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast/mod.rs
  core/src/ast/operator.rs
  core/src/ast/query.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/select/join.rs
  core/src/ast_builder/select/join_constraint.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/table.rs
  core/src/data/interval/string.rs
  core/src/data/string_ext.rs
  core/src/data/value/convert.rs
  core/src/data/value/mod.rs
  core/src/executor/alter/table.rs
  core/src/executor/alter/validate.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/select/blend.rs
  core/src/executor/select/mod.rs
  core/src/lib.rs
  core/src/plan/validate.rs
  core/src/translate/mod.rs
  gluesql-js/web/src/payload.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/src/lib.rs
  storages/sled-storage/benches/sled_benchmark.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/lib.rs
  test-suite/src/data_type/bytea.rs
  test-suite/src/data_type/int128.rs
  test-suite/src/data_type/uuid.rs
  test-suite/src/function/cast.rs
  test-suite/src/function/format.rs
  test-suite/src/function/gcd_lcm.rs
  test-suite/src/function/ifnull.rs
  test-suite/src/function/left_right.rs
  test-suite/src/function/lpad_rpad.rs
  test-suite/src/function/math_function.rs
  test-suite/src/function/sqrt_power.rs
  test-suite/src/function/substr.rs
  test-suite/src/index/showindexes.rs
  test-suite/src/inline_view.rs
  test-suite/src/lib.rs
  test-suite/src/like_ilike.rs
  utils/src/lib.rs
Labels: improvement

#862 Implement function `POSITION`
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/data/key.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/expr.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/position.rs
  test-suite/src/lib.rs
Labels: enhancement

#898 Implement to_sql func for SetExpr, Join
  core/src/ast/query.rs
  examples/query_parser.rs
Labels: enhancement

#896 Update test-suite select macros to support raw string literals for labels
  test-suite/src/blend.rs
  test-suite/src/series.rs
  test-suite/src/tester/macros.rs
Labels: improvement

#903 Add Send + Sync trait bounds to gluesql::Error::Storage variant
  core/src/result.rs
Labels: improvement

#880 [AST] Support `ArrayIndex`Expr
  core/src/ast/expr.rs
  core/src/data/value/selector.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/expr.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/mod.rs
  core/src/plan/planner.rs
  core/src/translate/expr.rs
  test-suite/src/data_type/list.rs
  test-suite/src/data_type/map.rs
  test-suite/src/tester/macros.rs
Labels: enhancement

#904 Upgrade sqlparser-rs to v0.24, migrate Interval from Literal to Expr
  core/Cargo.toml
  core/src/ast/ast_literal.rs
  core/src/ast/expr.rs
  core/src/data/interval/mod.rs
  core/src/data/interval/string.rs
  core/src/data/literal.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/parse_sql.rs
  core/src/plan/expr/mod.rs
  core/src/plan/planner.rs
  core/src/translate/ast_literal.rs
  core/src/translate/error.rs
  core/src/translate/expr.rs
  test-suite/src/alter/create_table.rs
  test-suite/src/arithmetic/error.rs
  test-suite/src/data_type/interval.rs
  test-suite/src/function/extract.rs
Labels: improvement

#906 Implement Key::to_be_bytes for Decimal variant
  core/src/data/key.rs
Labels: improvement

#910 [AST-Builder] Impl Case
  core/src/ast_builder/expr/case.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#915 Implement macro that implements `TryBinaryOperator`,
  core/src/data/value/binary_op/i8.rs
  core/src/data/value/binary_op/integer/i8.rs
  core/src/data/value/binary_op/integer/macros.rs
  core/src/data/value/binary_op/integer/mod.rs
  core/src/data/value/binary_op/integer/u8.rs
  core/src/data/value/binary_op/mod.rs
  core/src/data/value/binary_op/u8.rs
  core/src/data/value/convert.rs
  core/src/data/value/mod.rs
  test-suite/src/unary_operator.rs
Labels: improvement

#916 Implement hash join support to AST builder
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/filter.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/join/hash_join.rs
  core/src/ast_builder/select/join/join_constraint.rs
  core/src/ast_builder/select/join/mod.rs
  core/src/ast_builder/select/join/root.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
Labels: enhancement

#917 Grouping `GlueSQL` projects into `pkg/*` per language
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  pkg/javascript/.gitignore
  pkg/javascript/README.md
  pkg/javascript/examples/nodejs/main.js
  pkg/javascript/examples/web/module/README.md
  pkg/javascript/examples/web/module/index.html
  pkg/javascript/examples/web/rollup/index.html
  pkg/javascript/examples/web/rollup/main.js
  pkg/javascript/examples/web/rollup/package.json
  pkg/javascript/examples/web/rollup/rollup.config.js
  pkg/javascript/examples/web/webpack/index.html
  pkg/javascript/examples/web/webpack/main.js
  pkg/javascript/examples/web/webpack/package.json
  pkg/javascript/examples/web/webpack/webpack.config.js
  pkg/javascript/gluesql.js
  pkg/javascript/gluesql.node.js
  pkg/javascript/package.json
  pkg/javascript/web/.gitignore
  pkg/javascript/web/Cargo.toml
  pkg/javascript/web/README.md
  pkg/javascript/web/gluesql.js
  pkg/javascript/web/package.json
  pkg/javascript/web/rollup.config.js
  pkg/javascript/web/src/lib.rs
  pkg/javascript/web/src/payload.rs
  pkg/javascript/web/src/utils.rs
  pkg/javascript/web/tests/memory_storage.rs
  pkg/javascript/web/tests/payload.rs
  pkg/javascript/web/webdriver.json
  pkg/rust/Cargo.toml
  pkg/rust/examples/api_usage.rs
  pkg/rust/examples/hello_world.rs
  pkg/rust/examples/sled_multi_threaded.rs
  pkg/rust/examples/using_config.rs
  pkg/rust/src/lib.rs
  pkg/rust/src/main.rs
  pkg/rust/tests/glue.rs
Labels: improvement

#920 Add setting table_alias support to AST builder table init function
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/table.rs
Labels: improvement

#913 Move Expr::Cast structure to Expr::Function::Cast
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast_builder/expr/cast.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
  core/src/executor/alter/alter_table.rs
  core/src/executor/alter/index.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/plan/expr/mod.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/planner.rs
  core/src/translate/expr.rs
  core/src/translate/function.rs
Labels: improvement

#921 Add AST builder join nodes to query node conversion support
  core/src/ast_builder/query.rs
Labels: improvement

#923 Update AST builder between & hash_executor to accept different param …
  core/src/ast_builder/expr/between.rs
  core/src/ast_builder/select/join/hash_join.rs
  core/src/ast_builder/select/join/root.rs
Labels: improvement

#925 Add from ProjectNode & QueryNode for InListNode in AST builder,
  core/src/ast_builder/expr/in_list.rs
Labels: improvement

#928 Add a new method to Row which finds value by ident,
  core/src/data/row.rs
  core/src/executor/context/blend_context.rs
  core/src/executor/context/filter_context.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/sort.rs
  core/src/executor/validate.rs
Labels: improvement

#929 Replace plan/join.rs unit tests to use AST builder!
  core/src/plan/join.rs
Labels: improvement

#932 Simplify ast_builder/ QueryNode codes using decl macro
  core/src/ast_builder/query.rs
Labels: improvement

#931 [AST] to_sql for Function
  core/src/ast/ast_literal.rs
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast/mod.rs
  core/src/ast/query.rs
Labels: improvement

#938 Fix web/ payload data_type json serialization,
  pkg/javascript/web/src/payload.rs
  pkg/javascript/web/tests/memory_storage.rs
  pkg/javascript/web/tests/payload.rs
Labels: bug

#937 Use macro to generate SQL parsers
  core/src/ast_builder/assignment.rs
  core/src/parse_sql.rs
Labels: improvement

#942 Provide unsupported warning for select distinct
  core/src/translate/error.rs
  core/src/translate/query.rs
  test-suite/src/inline_view.rs
Labels: improvement

#943 Bump `uuid` version to `1.2.1`
  core/Cargo.toml
  core/src/data/value/json.rs
  test-suite/Cargo.toml
Labels: improvement

#946 Check for `Value::Null` in `Aggregate` except `*`,
  core/src/executor/aggregate/state.rs
  test-suite/src/aggregate/count.rs
  test-suite/src/aggregate/group_by.rs
Labels: bug

#945 Support `Expr::Case` in aggregate module
  core/src/executor/aggregate/mod.rs
  core/src/executor/aggregate/state.rs
  test-suite/src/aggregate/min.rs
  test-suite/src/aggregate/sum.rs
  test-suite/src/arithmetic/error.rs
  test-suite/src/inline_view.rs
Labels: enhancement

#948 fix: unmatced subquery should return Null (not error)
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/mod.rs
  test-suite/src/nested_select.rs
Labels: bug

#949 Fix test-suite tester::test to properly print expected & found labels
  test-suite/src/tester/mod.rs
Labels: bug

#940 Feat : Apply macros in i16 data type
  core/src/data/value/binary_op/i16.rs
  core/src/data/value/binary_op/integer/i16.rs
  core/src/data/value/binary_op/integer/macros.rs
  core/src/data/value/binary_op/integer/mod.rs
  core/src/data/value/binary_op/mod.rs
Labels: improvement

#930 Move Expr::Extract structure to Expr::Function::Extract
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast_builder/expr/extract.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/mod.rs
  core/src/data/key.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/plan/expr/mod.rs
  core/src/plan/planner.rs
  core/src/translate/expr.rs
  core/src/translate/function.rs
Labels: improvement

#881 [Ast] Implement ascii, chr function in ast
  core/src/ast/function.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/ascii.rs
  test-suite/src/function/chr.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#957 [ast_builder] update cast fn unit test
  core/src/ast_builder/expr/function.rs
Labels: improvement

#951 [FIx] add omitted uint8 integration test
  test-suite/src/data_type/mod.rs
  test-suite/src/data_type/uint8.rs
  test-suite/src/lib.rs
Labels: improvement

#955 Add AST builder integration tests of SELECT, UPDATE, INSERT and DELET…
  test-suite/src/ast_builder/delete.rs
  test-suite/src/ast_builder/insert.rs
  test-suite/src/ast_builder/mod.rs
  test-suite/src/ast_builder/select.rs
  test-suite/src/ast_builder/update.rs
  test-suite/src/lib.rs
Labels: improvement

#935 [Dictionary] support `GLUE_INDEXES`
  cli/src/print.rs
  core/src/ast/query.rs
  core/src/executor/fetch.rs
  core/src/translate/query.rs
  test-suite/src/dictionary_index.rs
  test-suite/src/lib.rs
Labels: enhancement

#960 fix: handle Error when DROP and CREATE PRIMARY INDEX manually
  core/src/translate/error.rs
  core/src/translate/mod.rs
  test-suite/src/dictionary_index.rs
Labels: bug

#962 Remove `macro-exports` in `data/../macros`
  core/src/data/value/binary_op/integer/i16.rs
  core/src/data/value/binary_op/integer/i8.rs
  core/src/data/value/binary_op/integer/macros.rs
  core/src/data/value/binary_op/integer/u8.rs
Labels: improvement

#963 Remove unneccesary syntax in enum Evaluated
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/update.rs
Labels: improvement

#899 [AST] CONCAT function concat with null return NULL
  core/src/executor/evaluate/function.rs
  test-suite/src/function/concat.rs
Labels: improvement

#967 Update AST builder ExprNode & ExprList to accept borrowed values
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/expr_list.rs
  core/src/ast_builder/select/order_by.rs
Labels: improvement

#971 Expose wasm-pack's init function argument to users
  pkg/javascript/gluesql.js
Labels: improvement

#965 [AST] Implement CONCAT_WS function In AST
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/concat_ws.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#973 [AST Builder] Implement CONCAT_WS function In AST Builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#979 Replace coverage badge to coveralls.io in pkg/javascript/README.md
  pkg/javascript/README.md
Labels: documentation
