Repository gluesql/gluesql, pull requests merged in 2022-06, with the labels that each got.

#591 Fix gluesql-js build and tests
  .github/workflows/rust.yml
  gluesql-js/web/package.json
  gluesql-js/web/src/payload.rs
  gluesql-js/web/tests/memory_storage.rs
  gluesql-js/web/tests/payload.rs
Labels: bug, improvement

#500 Implement shared memory storage
  Cargo.toml
  src/lib.rs
  storages/memory-storage/src/alter_table.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/Cargo.toml
  storages/shared-memory-storage/src/alter_table.rs
  storages/shared-memory-storage/src/index.rs
  storages/shared-memory-storage/src/lib.rs
  storages/shared-memory-storage/src/metadata.rs
  storages/shared-memory-storage/src/transaction.rs
  storages/shared-memory-storage/tests/concurrent_access.rs
  storages/shared-memory-storage/tests/shared_memory_storage.rs
Labels: enhancement

#554 Implement `ToSql` trait which displays AST as SQL text format
  core/src/ast/ast_literal.rs
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast/mod.rs
  core/src/ast/operator.rs
Labels: enhancement

#600 Add Description column to "show index from table" output
  cli/src/print.rs
  core/src/executor/execute.rs
  gluesql-js/web/src/payload.rs
  test-suite/src/index/showindexes.rs
Labels: improvement

#583 Ambiguous column selection should be detected while joining
  core/src/plan/error.rs
  core/src/plan/mod.rs
  core/src/plan/validate.rs
  core/src/result.rs
  test-suite/src/error.rs
Labels: enhancement

#606 Migrate cli/ clap-rs version to v3.2.2
  cli/Cargo.toml
  cli/src/lib.rs
Labels: improvement

#605 Fix SledStorage export & import multiple times bug,
  storages/sled-storage/src/lib.rs
  storages/sled-storage/tests/export_and_import.rs
Labels: bug

#607 Support `Deserialize` for `Payload`
  core/src/executor/execute.rs
Labels: improvement

#612 upgrade to Sqlparser 0.18
  core/Cargo.toml
Labels: improvement
