Repository gluesql/gluesql, pull requests merged in 2023-06, with the labels that each got.

#1233 Split custom Partial{Eq|Ord} impl of Value & Literal into evaluate_{eq|cmp}
  core/src/data/literal.rs
  core/src/data/value/binary_op/integer/macros.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/data/value/string.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  test-suite/src/ast_builder/function/text/position_and_indexing.rs
  test-suite/src/data_type/decimal.rs
  test-suite/src/function/abs.rs
  test-suite/src/function/ascii.rs
  test-suite/src/function/div_mod.rs
  test-suite/src/unary_operator.rs
Labels: improvement

#1238 fix: allow interval cast-related functions to accept only literals instead of evaluations
  Cargo.lock
  core/src/data/interval/error.rs
  core/src/data/interval/mod.rs
  core/src/data/interval/string.rs
  core/src/data/value/convert.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  storages/idb-storage/src/convert.rs
  storages/idb-storage/src/lib.rs
  storages/idb-storage/tests/convert.rs
  storages/json-storage/Cargo.toml
  storages/json-storage/src/lib.rs
  test-suite/src/data_type/time.rs
  test-suite/src/function/cast.rs
Labels: improvement

#1222 [AST Builder] Implement Geometic Point Type and Geometric Function in AST Builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1244 [AST Builder] Implement ascii, chr function in ast
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1242 Implement MD5 Function
  Cargo.lock
  core/Cargo.toml
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/md5.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1246 Remove test function in test-suite tester,
  storages/json-storage/tests/error.rs
  storages/json-storage/tests/json_dml.rs
  storages/json-storage/tests/primary_key.rs
  storages/json-storage/tests/schema.rs
  storages/json-storage/tests/schemaless.rs
  test-suite/src/ast_builder/alias_as.rs
  test-suite/src/ast_builder/delete.rs
  test-suite/src/ast_builder/expr/pattern_matching.rs
  test-suite/src/ast_builder/function/datetime/conversion.rs
  test-suite/src/ast_builder/function/datetime/current_date_and_time.rs
  test-suite/src/ast_builder/function/datetime/formatting.rs
  test-suite/src/ast_builder/function/math/basic_arithmetic.rs
  test-suite/src/ast_builder/function/math/conversion.rs
  test-suite/src/ast_builder/function/math/rounding.rs
  test-suite/src/ast_builder/function/other/ifnull.rs
  test-suite/src/ast_builder/function/text/case_conversion.rs
  test-suite/src/ast_builder/function/text/position_and_indexing.rs
  test-suite/src/ast_builder/function/text/trimming.rs
  test-suite/src/ast_builder/insert.rs
  test-suite/src/ast_builder/select.rs
  test-suite/src/ast_builder/statements/querying/data_aggregation.rs
  test-suite/src/ast_builder/update.rs
  test-suite/src/ast_builder/values.rs
  test-suite/src/tester/mod.rs
Labels: improvement

#1253 ci: Automatically assign a PR to its author
  .github/auto-author-assign-config.yml
  .github/workflows/auto-author-assign.yml
Labels: improvement

#1251 Replace `actions-rs/toolchain` with `dtolnay/rust-toolchain`
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
Labels: improvement

#1256 Change console.log in gluesql.js -> console.debug
  pkg/javascript/src/lib.rs
Labels: good first issue, improvement

#1258 Wrap config path by quotes in auto-author-assign.yml
  .github/workflows/auto-author-assign.yml
Labels: bug
