Repository gluesql/gluesql, pull requests merged in 2023-09, with the labels that each got.

#1341 Implement `ADD_MONTH` function
  core/src/ast/function.rs
  core/src/data/value/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/add_month.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1375 feat: implement ast_builder for values function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1404 chore: remove `Result` from `ast_builder::transaction` return type
  core/src/ast_builder/transaction.rs
  test-suite/src/lib.rs
  test-suite/src/transaction/ast_builder.rs
  test-suite/src/transaction/mod.rs
Labels: improvement

#1394 Bitwise Shift Right Operator Implementation
  core/src/ast/operator.rs
  core/src/ast_builder/expr/binary_op.rs
  core/src/data/literal.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/translate/operator.rs
  test-suite/src/bitwise_shift_left.rs
  test-suite/src/bitwise_shift_right.rs
  test-suite/src/lib.rs
Labels: enhancement

#1398 refactor: update function module's namespacing in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  test-suite/src/ast_builder/function/datetime/conversion.rs
  test-suite/src/ast_builder/function/datetime/current_date_and_time.rs
  test-suite/src/ast_builder/function/datetime/formatting.rs
  test-suite/src/ast_builder/function/math/basic_arithmetic.rs
  test-suite/src/ast_builder/function/math/conversion.rs
  test-suite/src/ast_builder/function/math/rounding.rs
  test-suite/src/ast_builder/function/other/coalesce.rs
  test-suite/src/ast_builder/function/other/ifnull.rs
  test-suite/src/ast_builder/function/text/case_conversion.rs
  test-suite/src/ast_builder/function/text/position_and_indexing.rs
  test-suite/src/ast_builder/function/text/trimming.rs
Labels: improvement

#1399 refactor: remove implementation of from<Value> trait for Evaluated
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
Labels: improvement

#1401 chore: implement `ConvertError`,
  core/src/data/mod.rs
  core/src/data/value/convert.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/limit.rs
  core/src/result.rs
  test-suite/src/function/cast.rs
Labels: improvement

#1397 fix: Literal comparison with BinaryOperator
  core/src/executor/evaluate/expr.rs
  test-suite/src/ordering.rs
Labels: bug

#1361 Remove eval_to_{int|float..} macro uses in core/../evaluate/function.rs,
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  test-suite/src/function/geometry/calc_distance.rs
Labels: improvement

#1415 Reflect Deprecation of `from_utc` in Crate `chrono`
  core/src/data/value/expr.rs
  core/src/data/value/json.rs
Labels: improvement
