Repository gluesql/gluesql, pull requests merged in 2023-02, with the labels that each got.

#1068 Add CompositeStorage which bundles multiple storages
  core/src/ast/mod.rs
  core/src/ast_builder/create_table.rs
  core/src/data/schema.rs
  core/src/executor/alter/table.rs
  core/src/executor/execute.rs
  core/src/translate/mod.rs
  storages/composite-storage/Cargo.toml
  storages/composite-storage/src/lib.rs
  storages/composite-storage/src/store.rs
  storages/composite-storage/src/store_mut.rs
  storages/composite-storage/src/transaction.rs
  storages/composite-storage/tests/basic.rs
  storages/composite-storage/tests/composite_storage.rs
  storages/composite-storage/tests/error.rs
  storages/composite-storage/tests/memory_and_sled.rs
  storages/memory-storage/src/transaction.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index_mut.rs
Labels: enhancement

#999 Add enum `StrSlice` under enum `Evaluated`
  core/src/ast_builder/expr/function.rs
  core/src/data/key.rs
  core/src/data/literal.rs
  core/src/data/value/mod.rs
  core/src/data/value/string.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/update.rs
  test-suite/src/concat.rs
  test-suite/src/function/cast.rs
  test-suite/src/function/ltrim_rtrim.rs
  test-suite/src/function/substr.rs
  test-suite/src/function/trim.rs
  test-suite/src/like_ilike.rs
  test-suite/src/nullable.rs
  test-suite/src/primary_key.rs
  test-suite/src/schemaless/error.rs
  test-suite/src/update.rs
Labels: improvement

#1082 Update `StringExt` implementation to use `str`
  core/src/data/literal.rs
  core/src/data/string_ext.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/data/value/string.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
Labels: improvement

#1080 Add inet datatype
  cli/tests/dump.rs
  core/src/ast/data_type.rs
  core/src/data/bigdecimal_ext.rs
  core/src/data/key.rs
  core/src/data/value/convert.rs
  core/src/data/value/error.rs
  core/src/data/value/expr.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/translate/data_type.rs
  test-suite/src/data_type/inet.rs
  test-suite/src/data_type/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1086 Refactor CreateTable.columns from `Vec<ColumnDef>` to `Option<Vec<ColumnDef>>`
  core/src/ast/mod.rs
  core/src/ast_builder/create_table.rs
  core/src/data/schema.rs
  core/src/executor/alter/table.rs
  core/src/executor/execute.rs
  core/src/translate/mod.rs
Labels: improvement

#1084 Apply CompositeStorage to JS package
  core/src/plan/mock.rs
  core/src/store/transaction.rs
  pkg/javascript/examples/nodejs/main.js
  pkg/javascript/examples/web/module/index.html
  pkg/javascript/examples/web/rollup/main.js
  pkg/javascript/examples/web/rollup/package.json
  pkg/javascript/examples/web/webpack/main.js
  pkg/javascript/examples/web/webpack/package.json
  pkg/javascript/web/Cargo.toml
  pkg/javascript/web/package.json
  pkg/javascript/web/src/lib.rs
  pkg/javascript/web/tests/composite_storage.rs
  pkg/javascript/web/tests/error.rs
  pkg/javascript/web/tests/join_multiple_storages.rs
  pkg/javascript/web/tests/memory_storage.rs
Labels: improvement

#1089 Support `Schema::from_ddl(ddl: &str) -> String`
  core/src/data/mod.rs
  core/src/data/schema.rs
  core/src/result.rs
Labels: enhancement

#1090 Update IdbStorage to use Schema::{to_ddl, from_ddl} to manage schema …
  storages/idb-storage/src/lib.rs
Labels: improvement

#1091 Remove Store trait related cfg features,
  .github/workflows/rust.yml
  cli/Cargo.toml
  core/Cargo.toml
  core/src/ast/mod.rs
  core/src/ast_builder/alter_table.rs
  core/src/ast_builder/index.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/table_name.rs
  core/src/ast_builder/transaction.rs
  core/src/data/schema.rs
  core/src/executor/alter/alter_table.rs
  core/src/executor/alter/index.rs
  core/src/executor/alter/mod.rs
  core/src/executor/execute.rs
  core/src/executor/fetch.rs
  core/src/executor/mod.rs
  core/src/plan/mock.rs
  core/src/result.rs
  core/src/store/mod.rs
  core/src/translate/ddl.rs
  core/src/translate/mod.rs
  pkg/rust/Cargo.toml
  storages/composite-storage/Cargo.toml
  storages/composite-storage/src/lib.rs
  storages/composite-storage/src/transaction.rs
  storages/composite-storage/tests/error.rs
  storages/composite-storage/tests/memory_and_sled.rs
  storages/idb-storage/Cargo.toml
  storages/idb-storage/src/lib.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/src/alter_table.rs
  storages/memory-storage/src/index.rs
  storages/memory-storage/src/transaction.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/shared-memory-storage/Cargo.toml
  storages/sled-storage/Cargo.toml
  storages/web-storage/Cargo.toml
  storages/web-storage/src/lib.rs
  test-suite/Cargo.toml
  test-suite/src/alter/alter_table.rs
  test-suite/src/alter/drop_indexed.rs
  test-suite/src/alter/mod.rs
  test-suite/src/index/mod.rs
  test-suite/src/lib.rs
  test-suite/src/transaction/alter_table.rs
  test-suite/src/transaction/basic.rs
  test-suite/src/transaction/dictionary.rs
  test-suite/src/transaction/index.rs
  test-suite/src/transaction/mod.rs
Labels: improvement

#1041 Support Values Query at ASTBuilder
  core/src/ast_builder/mod.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/filter.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/having.rs
  core/src/ast_builder/select/join/hash_join.rs
  core/src/ast_builder/select/join/join_constraint.rs
  core/src/ast_builder/select/join/mod.rs
  core/src/ast_builder/select/join/root.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/offset_limit.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/select/values.rs
  test-suite/src/ast_builder/mod.rs
  test-suite/src/ast_builder/values.rs
  test-suite/src/lib.rs
Labels: enhancement

#1093 Fix typo in plan/validate.rs
  core/src/plan/validate.rs
Labels: improvement

#1092 Add `core/data` module unit tests
  core/src/data/key.rs
  core/src/data/value/convert.rs
Labels: improvement

#1094 Add "cli" unittest
  cli/src/command.rs
  cli/src/print.rs
Labels: improvement

#1101 Remove `Rc` from `ColumnValidation`
  core/src/executor/execute.rs
  core/src/executor/insert.rs
  core/src/executor/validate.rs
Labels: improvement

#1102 Replace `TryStream` to `Stream`
  core/src/executor/aggregate/mod.rs
  core/src/executor/fetch.rs
  core/src/executor/join.rs
  core/src/executor/select/mod.rs
Labels: improvement

#1104 Remove stream unneeded map ok uses
  core/src/executor/fetch.rs
  core/src/executor/select/project.rs
  core/src/plan/schema.rs
Labels: improvement

#1103 Replace `Box::pin` to `futures_enum::Stream`
  core/src/executor/limit.rs
  core/src/executor/select/mod.rs
Labels: improvement

#1105 Remove `Error::Storage` variant
  core/src/result.rs
  storages/sled-storage/src/error.rs
  storages/sled-storage/tests/export_and_import.rs
Labels: improvement

#1106 Remove `Rc` in `validate.rs`
  core/src/executor/validate.rs
Labels: improvement

#1107 Fix error handling for `ilike` function on `Literal` being treated as…
  core/src/data/literal.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  test-suite/src/like_ilike.rs
Labels: improvement

#1053 Support `Jsonl` Storage
  cli/src/lib.rs
  core/src/data/mod.rs
  core/src/data/schema.rs
  core/src/data/value/convert.rs
  storages/jsonl-storage/Cargo.toml
  storages/jsonl-storage/src/alter_table.rs
  storages/jsonl-storage/src/error.rs
  storages/jsonl-storage/src/index.rs
  storages/jsonl-storage/src/lib.rs
  storages/jsonl-storage/src/store.rs
  storages/jsonl-storage/src/store_mut.rs
  storages/jsonl-storage/src/transaction.rs
  storages/jsonl-storage/tests/error.rs
  storages/jsonl-storage/tests/jsonl_storage.rs
  storages/jsonl-storage/tests/primary_key.rs
  storages/jsonl-storage/tests/samples/Schema.jsonl
  storages/jsonl-storage/tests/samples/Schema.sql
  storages/jsonl-storage/tests/samples/Schemaless.jsonl
  storages/jsonl-storage/tests/samples/WrongFormat.jsonl
  storages/jsonl-storage/tests/samples/WrongSchema.jsonl
  storages/jsonl-storage/tests/samples/WrongSchema.sql
  storages/jsonl-storage/tests/samples/WrongTableName.jsonl
  storages/jsonl-storage/tests/samples/WrongTableName.sql
  storages/jsonl-storage/tests/schema.rs
  storages/jsonl-storage/tests/schemaless.rs
Labels: enhancement

#1108 docs(javascript): update examples link
  pkg/javascript/README.md
Labels: documentation
