Repository gluesql/gluesql, pull requests merged in 2023-01, with the labels that each got.

#1055 Replace `Box::pin` to `futures_enum` in aggregate module
  core/src/executor/aggregate/mod.rs
Labels: improvement

#1056 Bump `sqlparser` version to `0.30`
  core/Cargo.toml
  core/src/parse_sql.rs
  core/src/translate/data_type.rs
  core/src/translate/ddl.rs
  core/src/translate/expr.rs
  core/src/translate/function.rs
  core/src/translate/query.rs
  test-suite/src/data_type/bytea.rs
  test-suite/src/function/ceil.rs
  test-suite/src/function/floor.rs
Labels: improvement

#1057 Bump rust-toolchain version to `1.66`
  core/src/data/interval/primitive.rs
  core/src/executor/aggregate/state.rs
  core/src/plan/schema.rs
  rust-toolchain
  storages/memory-storage/src/lib.rs
  storages/sled-storage/src/gc.rs
Labels: improvement

#1063 Implement Rand function
  core/Cargo.toml
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/rand.rs
  test-suite/src/lib.rs
Labels: enhancement

#1067 Add IndexedDB storage support
  .github/workflows/rust.yml
  core/src/data/key.rs
  core/src/data/value/convert.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  storages/idb-storage/Cargo.toml
  storages/idb-storage/README.md
  storages/idb-storage/src/convert.rs
  storages/idb-storage/src/error.rs
  storages/idb-storage/src/lib.rs
  storages/idb-storage/tests/convert.rs
  storages/idb-storage/tests/idb_storage.rs
  test-suite/src/data_type/int64.rs
Labels: enhancement

#1058 Remove `clone` in `check_table_factor`
  core/src/plan/evaluable.rs
Labels: improvement

#1065 Support column alias for Table, Derived Table
  core/src/executor/fetch.rs
  test-suite/src/basic.rs
  test-suite/src/column_alias.rs
  test-suite/src/lib.rs
  test-suite/src/values.rs
Labels: enhancement

#1071 Change StoreMut interface to use &mut self, not to take ownership
  core/src/plan/mock.rs
  core/src/result.rs
  core/src/store/mod.rs
  storages/idb-storage/src/lib.rs
  storages/memory-storage/src/lib.rs
  storages/shared-memory-storage/src/lib.rs
  storages/sled-storage/src/store_mut.rs
  storages/sled-storage/tests/sled_transaction.rs
  storages/web-storage/src/lib.rs
Labels: improvement

#883 Implement ValidationContext(schema_map + alias) to enhance validation of ambiguous columns
  core/src/plan/mod.rs
  core/src/plan/schema.rs
  core/src/plan/validate.rs
  test-suite/src/join.rs
Labels: improvement

#1072 Update all store mut trait methods to take &mut self
  cli/src/lib.rs
  cli/tests/dump.rs
  core/src/executor/alter/alter_table.rs
  core/src/executor/alter/index.rs
  core/src/executor/alter/table.rs
  core/src/executor/execute.rs
  core/src/executor/insert.rs
  core/src/plan/mock.rs
  core/src/store/alter_table.rs
  core/src/store/index.rs
  core/src/store/mod.rs
  core/src/store/transaction.rs
  storages/idb-storage/src/lib.rs
  storages/memory-storage/src/alter_table.rs
  storages/memory-storage/src/index.rs
  storages/memory-storage/src/transaction.rs
  storages/shared-memory-storage/src/alter_table.rs
  storages/shared-memory-storage/src/index.rs
  storages/shared-memory-storage/src/lib.rs
  storages/shared-memory-storage/src/transaction.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/lib.rs
  storages/sled-storage/src/transaction.rs
  storages/sled-storage/tests/sled_transaction.rs
  storages/web-storage/src/lib.rs
Labels: improvement

#1073 Remove `MutResult`
  cli/tests/dump.rs
  core/src/executor/execute.rs
  core/src/glue.rs
  core/src/plan/mock.rs
  core/src/result.rs
  pkg/javascript/web/src/lib.rs
  pkg/rust/examples/api_usage.rs
  storages/sled-storage/tests/export_and_import.rs
  storages/sled-storage/tests/sled_transaction.rs
  test-suite/src/tester/mod.rs
Labels: improvement

#1075 Replace `dyn object` to generic
  core/src/executor/aggregate/mod.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/fetch.rs
  core/src/executor/filter.rs
  core/src/executor/join.rs
  core/src/executor/select/mod.rs
  core/src/executor/select/project.rs
  core/src/executor/sort.rs
  core/src/executor/update.rs
  core/src/executor/validate.rs
  core/src/plan/mod.rs
  core/src/plan/schema.rs
Labels: improvement

#1074 Fix `plan::validate` to handle `CTAS` and `ITAS` adding unit test
  core/src/plan/schema.rs
  core/src/plan/validate.rs
  test-suite/src/join.rs
Labels: bug
