Repository gluesql/gluesql, pull requests merged in 2023-03, with the labels that each got.

#1112 join_expr when in_subquery, exists expr in join constraint
  core/src/plan/join.rs
Labels: improvement

#1110 Add Ord impl for Key,
  core/src/data/interval/mod.rs
  core/src/data/key.rs
  core/src/data/value/mod.rs
  storages/jsonl-storage/src/store_mut.rs
Labels: improvement

#1100 Implement `FIND_IDX` function
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/data/key.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/find_idx.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1114 Add `f64` support to `data::Key`
  core/Cargo.toml
  core/src/data/key.rs
  core/src/data/value/mod.rs
  core/src/executor/select/mod.rs
  core/src/executor/sort.rs
  storages/jsonl-storage/src/store_mut.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/store.rs
  storages/sled-storage/src/store_mut.rs
  test-suite/src/aggregate/error.rs
  test-suite/src/aggregate/group_by.rs
  test-suite/src/lib.rs
Labels: improvement

#1115 Fix MemoryStorage & WebStorage primary key support
  storages/memory-storage/Cargo.toml
  storages/memory-storage/src/lib.rs
  storages/web-storage/src/lib.rs
  test-suite/src/primary_key.rs
Labels: bug

#1117 Pass data even when `deleted_by` is not present
  storages/sled-storage/src/snapshot.rs
  storages/sled-storage/tests/sled_storage.rs
Labels: bug

#1118 Replace closure to variable in `data/interval` module
  core/src/data/interval/mod.rs
Labels: improvement

#1119 fix column alias with identifer
  core/src/executor/fetch.rs
  test-suite/src/column_alias.rs
Labels: bug

#1121 Keep `Cargo.lock`
  .gitignore
  Cargo.lock
Labels: improvement

#1122 docs(readme): add discord icon to chat badge
  README.md
Labels: documentation

#1125 Bump rust version to 1.68
  core/src/data/value/mod.rs
  core/src/executor/fetch.rs
  core/src/executor/select/mod.rs
  rust-toolchain
Labels: improvement

#1123 Support `JSON` format in `JSONL storage`
  core/src/data/value/json.rs
  storages/jsonl-storage/Cargo.toml
  storages/jsonl-storage/src/error.rs
  storages/jsonl-storage/src/lib.rs
  storages/jsonl-storage/src/store.rs
  storages/jsonl-storage/src/store_mut.rs
  storages/jsonl-storage/tests/error.rs
  storages/jsonl-storage/tests/json_dml.rs
  storages/jsonl-storage/tests/samples/ArrayOfJsonsSchema.json
  storages/jsonl-storage/tests/samples/ArrayOfJsonsSchema.sql
  storages/jsonl-storage/tests/samples/ArrayOfJsonsSchemaless.json
  storages/jsonl-storage/tests/samples/Duplicated.json
  storages/jsonl-storage/tests/samples/Duplicated.jsonl
  storages/jsonl-storage/tests/samples/JsonArrayTypeRequired.json
  storages/jsonl-storage/tests/samples/JsonObjectTypeRequired.json
  storages/jsonl-storage/tests/samples/SingleJsonSchema.json
  storages/jsonl-storage/tests/samples/SingleJsonSchema.sql
  storages/jsonl-storage/tests/samples/SingleJsonSchemaless.json
  storages/jsonl-storage/tests/samples/WrongFormat.jsonl
  storages/jsonl-storage/tests/samples/WrongFormatJson.json
  storages/jsonl-storage/tests/samples/WrongFormatJsonl.jsonl
  storages/jsonl-storage/tests/samples/WrongSchema.jsonl
  storages/jsonl-storage/tests/samples/WrongTableName.jsonl
  storages/jsonl-storage/tests/schema.rs
  storages/jsonl-storage/tests/schemaless.rs
Labels: enhancement
