Repository gluesql/gluesql, pull requests merged in 2023-05, with the labels that each got.

#1167 Add documentation for text functions in SQL
  docs/docs/sql-syntax/functions/text/ascii.md
  docs/docs/sql-syntax/functions/text/chr.md
  docs/docs/sql-syntax/functions/text/concat-ws.md
  docs/docs/sql-syntax/functions/text/concat.md
  docs/docs/sql-syntax/functions/text/find-idx.md
  docs/docs/sql-syntax/functions/text/initcap.md
  docs/docs/sql-syntax/functions/text/left.md
  docs/docs/sql-syntax/functions/text/lower.md
  docs/docs/sql-syntax/functions/text/lpad.md
  docs/docs/sql-syntax/functions/text/ltrim.md
  docs/docs/sql-syntax/functions/text/position.md
  docs/docs/sql-syntax/functions/text/repeat.md
  docs/docs/sql-syntax/functions/text/reverse.md
  docs/docs/sql-syntax/functions/text/right.md
  docs/docs/sql-syntax/functions/text/rpad.md
  docs/docs/sql-syntax/functions/text/rtrim.md
  docs/docs/sql-syntax/functions/text/substr.md
  docs/docs/sql-syntax/functions/text/trim.md
  docs/docs/sql-syntax/functions/text/upper.md
Labels: documentation

#1175 Update global Error enum to display with error module prefix
  core/src/result.rs
Labels: improvement

#1172 Add doc for datetime, geometry, list & map and other functions,
  docs/docs/sql-syntax/functions/datetime/extract.md
  docs/docs/sql-syntax/functions/datetime/format.md
  docs/docs/sql-syntax/functions/datetime/now.md
  docs/docs/sql-syntax/functions/datetime/to-date.md
  docs/docs/sql-syntax/functions/datetime/to-time.md
  docs/docs/sql-syntax/functions/datetime/to-timestamp.md
  docs/docs/sql-syntax/functions/geometry/calc-distance.md
  docs/docs/sql-syntax/functions/geometry/get-x.md
  docs/docs/sql-syntax/functions/geometry/get-y.md
  docs/docs/sql-syntax/functions/geometry/point.md
  docs/docs/sql-syntax/functions/list-map/append.md
  docs/docs/sql-syntax/functions/list-map/concat.md
  docs/docs/sql-syntax/functions/list-map/prepend.md
  docs/docs/sql-syntax/functions/others/cast.md
  docs/docs/sql-syntax/functions/others/generate-uuid.md
  docs/docs/sql-syntax/functions/others/if-null.md
  docs/docs/sql-syntax/functions/others/ifnull.md
Labels: documentation

#1173 Add documentation for math functions
  docs/docs/sql-syntax/functions/math/abs.md
  docs/docs/sql-syntax/functions/math/acos.md
  docs/docs/sql-syntax/functions/math/asin.md
  docs/docs/sql-syntax/functions/math/atan.md
  docs/docs/sql-syntax/functions/math/ceil.md
  docs/docs/sql-syntax/functions/math/cos.md
  docs/docs/sql-syntax/functions/math/degrees.md
  docs/docs/sql-syntax/functions/math/div.md
  docs/docs/sql-syntax/functions/math/exp.md
  docs/docs/sql-syntax/functions/math/floor.md
  docs/docs/sql-syntax/functions/math/gcd.md
  docs/docs/sql-syntax/functions/math/lcm.md
  docs/docs/sql-syntax/functions/math/ln.md
  docs/docs/sql-syntax/functions/math/log.md
  docs/docs/sql-syntax/functions/math/log10.md
  docs/docs/sql-syntax/functions/math/log2.md
  docs/docs/sql-syntax/functions/math/mod.md
  docs/docs/sql-syntax/functions/math/pi.md
  docs/docs/sql-syntax/functions/math/power.md
  docs/docs/sql-syntax/functions/math/radians.md
  docs/docs/sql-syntax/functions/math/rand.md
  docs/docs/sql-syntax/functions/math/randians.md
  docs/docs/sql-syntax/functions/math/round.md
  docs/docs/sql-syntax/functions/math/sign.md
  docs/docs/sql-syntax/functions/math/sin.md
  docs/docs/sql-syntax/functions/math/sqrt.md
  docs/docs/sql-syntax/functions/math/tan.md
Labels: documentation

#1170 Add documentation for Json Storage
  docs/docs/storages/supported-storages/json-storage.md
Labels: documentation

#1177 Add nullable, key, default to `GLUE_TABLE_COLUMNS`
  core/src/executor/fetch.rs
  test-suite/src/dictionary.rs
Labels: improvement

#1184 Add documentation layout for AstBuilder
  docs/docs/ast-builder/expressions/_category_.json
  docs/docs/ast-builder/expressions/conditional.md
  docs/docs/ast-builder/expressions/nested.md
  docs/docs/ast-builder/expressions/operator-based.md
  docs/docs/ast-builder/expressions/pattern-matching.md
  docs/docs/ast-builder/expressions/value-checking.md
  docs/docs/ast-builder/functions/_category_.json
  docs/docs/ast-builder/functions/date-&-time/_category_.json
  docs/docs/ast-builder/functions/date-&-time/conversion.md
  docs/docs/ast-builder/functions/date-&-time/current-date-and-time.md
  docs/docs/ast-builder/functions/date-&-time/date-and-time-extraction.md
  docs/docs/ast-builder/functions/date-&-time/formatting.md
  docs/docs/ast-builder/functions/geometry/_category_.json
  docs/docs/ast-builder/functions/geometry/coordinate-extraction.md
  docs/docs/ast-builder/functions/geometry/distance-calculation.md
  docs/docs/ast-builder/functions/geometry/point-creation.md
  docs/docs/ast-builder/functions/list-&-map/_category_.json
  docs/docs/ast-builder/functions/list-&-map/list-and-map-concatenation.md
  docs/docs/ast-builder/functions/list-&-map/list-manipulation.md
  docs/docs/ast-builder/functions/math/_category_.json
  docs/docs/ast-builder/functions/math/basic-arithmetic.md
  docs/docs/ast-builder/functions/math/conversion.md
  docs/docs/ast-builder/functions/math/logarithmic-and-exponential.md
  docs/docs/ast-builder/functions/math/rounding.md
  docs/docs/ast-builder/functions/math/special-mathematical.md
  docs/docs/ast-builder/functions/math/trigonometric.md
  docs/docs/ast-builder/functions/others/_category_.json
  docs/docs/ast-builder/functions/others/null-handling.md
  docs/docs/ast-builder/functions/others/type-conversion.md
  docs/docs/ast-builder/functions/others/unique-identifier.md
  docs/docs/ast-builder/functions/text/_category_.json
  docs/docs/ast-builder/functions/text/case-conversion.md
  docs/docs/ast-builder/functions/text/character-conversion.md
  docs/docs/ast-builder/functions/text/padding.md
  docs/docs/ast-builder/functions/text/position-and-indexing.md
  docs/docs/ast-builder/functions/text/text-manipulation.md
  docs/docs/ast-builder/functions/text/trimming.md
  docs/docs/ast-builder/statements/_category_.json
  docs/docs/ast-builder/statements/data-manipulation/_category_.json
  docs/docs/ast-builder/statements/data-manipulation/deleting-data.md
  docs/docs/ast-builder/statements/data-manipulation/inserting-data.md
  docs/docs/ast-builder/statements/data-manipulation/updating-data.md
  docs/docs/ast-builder/statements/querying/_category_.json
  docs/docs/ast-builder/statements/querying/creating-derived-subqueries.md
  docs/docs/ast-builder/statements/querying/data-aggregation.md
  docs/docs/ast-builder/statements/querying/data-injection.md
  docs/docs/ast-builder/statements/querying/data-joining.md
  docs/docs/ast-builder/statements/querying/data-selection-and-projection.md
  docs/docs/ast-builder/statements/querying/data-sorting-and-limiting.md
  docs/docs/ast-builder/statements/querying/fetching-data-from-storage.md
  docs/docs/ast-builder/statements/querying/using-preloaded-data.md
Labels: documentation

#1185 Fix InvalidJsonString error message replacing payload to fileName
  storages/json-storage/src/error.rs
  storages/json-storage/src/lib.rs
  storages/json-storage/tests/error.rs
Labels: bug

#1186 Add rounding test cases for ast_builder
  test-suite/src/ast_builder/function/math/mod.rs
  test-suite/src/ast_builder/function/math/rounding.rs
  test-suite/src/ast_builder/function/mod.rs
  test-suite/src/ast_builder/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1191 Added documentation for the round, ceil, and floor functions in ast-builder
  docs/docs/ast-builder/functions/math/rounding.md
Labels: documentation

#1192 Add math conversion docs for ast_builder
  docs/docs/ast-builder/functions/math/conversion.md
Labels: documentation

#1189 Add math conversion test case for ast_builder
  test-suite/src/ast_builder/function/math/conversion.rs
  test-suite/src/ast_builder/function/math/mod.rs
  test-suite/src/ast_builder/function/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1187 Add datetime conversion test cases for ast_builder
  test-suite/src/ast_builder/function/datetime/conversion.rs
  test-suite/src/ast_builder/function/datetime/mod.rs
  test-suite/src/ast_builder/function/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1193 Add Testcase/case conversion
  test-suite/src/ast_builder/function/mod.rs
  test-suite/src/ast_builder/function/text/case_conversion.rs
  test-suite/src/ast_builder/function/text/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1195 add Docs/case conversion(upper, lower, InitCap) in ast builder
  docs/docs/ast-builder/functions/text/case-conversion.md
Labels: documentation

#1190 Add test code function / text / trimming
  test-suite/src/ast_builder/function/mod.rs
  test-suite/src/ast_builder/function/text/mod.rs
  test-suite/src/ast_builder/function/text/trimming.rs
  test-suite/src/lib.rs
Labels: improvement

#1196 Add doc about the function Date & Time Conversion
  docs/docs/ast-builder/functions/date-&-time/conversion.md
Labels: documentation

#1197 Add ast builder Trimming function docs
  docs/docs/ast-builder/functions/text/trimming.md
Labels: documentation

#1194 Add pattern_matching test cases for ast_builder
  test-suite/src/ast_builder/expr/mod.rs
  test-suite/src/ast_builder/expr/pattern_matching.rs
  test-suite/src/ast_builder/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1199 Add pattern-matching doc for ast_builder
  docs/docs/ast-builder/expressions/pattern-matching.md
Labels: documentation

#1198 Add testcase/formatting for ast_builder
  test-suite/src/ast_builder/function/datetime/formatting.rs
  test-suite/src/ast_builder/function/datetime/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1202 Update math basic arithmetic docs for ast_builder
  docs/docs/ast-builder/functions/math/basic-arithmetic.md
Labels: documentation

#1200 Add docs/formatting for ast_builder
  docs/docs/ast-builder/functions/date-&-time/formatting.md
Labels: documentation

#1201 Add math basic arithmetic test case for ast_builder
  test-suite/src/ast_builder/function/math/basic_arithmetic.rs
  test-suite/src/ast_builder/function/math/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1203 Add Position and Indexing test code
  test-suite/src/ast_builder/function/text/mod.rs
  test-suite/src/ast_builder/function/text/position_and_indexing.rs
  test-suite/src/lib.rs
Labels: improvement

#1206 docs: write position and indexing docs
  docs/docs/ast-builder/functions/text/position-and-indexing.md
Labels: documentation

#1205 Add datetime current date and time test case for ast builder
  test-suite/src/ast_builder/function/datetime/current_date_and_time.rs
  test-suite/src/ast_builder/function/datetime/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1207 Add ifnull test suite for ast_builder
  test-suite/src/ast_builder/function/mod.rs
  test-suite/src/ast_builder/function/other/ifnull.rs
  test-suite/src/ast_builder/function/other/mod.rs
  test-suite/src/lib.rs
Labels: improvement

#1208 Add document of datetime current date and time for ast-builder
  docs/docs/ast-builder/functions/date-&-time/conversion.md
  docs/docs/ast-builder/functions/date-&-time/current-date-and-time.md
Labels: documentation

#1209 Add ast_builder null handling doc
  docs/docs/ast-builder/functions/others/null-handling.md
Labels: documentation

#1211 Add a case for insert with source
  test-suite/src/insert.rs
Labels: improvement

#1183 Add documentation for CLI
  docs/docs/getting-started/cli.md
Labels: documentation

#1213 Fix docs/ Discord GlueSQL channel invite link address
  docs/docusaurus.config.js
Labels: bug, documentation

#1212 Setup blog based on docusaurus,
  docs/blog/2023-05-18-test.md
  docs/docusaurus.config.js
  docs/package.json
Labels: improvement

#1214 Fix docusaurus pages/index broken link
  docs/src/pages/index.js
Labels: bug

#1210 Remove pkg/js rollup custom build,
  .github/workflows/javascript.yml
  Cargo.toml
  docs/docs/getting-started/javascript-web.md
  pkg/javascript/.gitignore
  pkg/javascript/Cargo.toml
  pkg/javascript/DEVELOPMENT.md
  pkg/javascript/examples/web/rollup/package.json
  pkg/javascript/examples/web/rollup/rollup.config.js
  pkg/javascript/gluesql.rollup.js
  pkg/javascript/package.json
  pkg/javascript/src/lib.rs
  pkg/javascript/src/payload.rs
  pkg/javascript/src/utils.rs
  pkg/javascript/tests/composite_storage.rs
  pkg/javascript/tests/error.rs
  pkg/javascript/tests/join_multiple_storages.rs
  pkg/javascript/tests/payload.rs
  pkg/javascript/web/.gitignore
  pkg/javascript/web/gluesql.js
  pkg/javascript/web/package.json
  pkg/javascript/web/rollup.config.js
  pkg/javascript/webdriver.json
Labels: improvement

#1216 Update docs/ - intro page, icon, sidebar settings, etc...
  docs/README.md
  docs/docs/ast-builder/_category_.json
  docs/docs/getting-started/_category_.json
  docs/docs/index.md
  docs/docs/intro.md
  docs/docs/sql-syntax/_category_.json
  docs/docs/sql-syntax/functions/_category_.json
  docs/docs/sql-syntax/statements/_category_.json
  docs/docs/storages/_category_.json
  docs/docs/storages/developing-custom-storages/_category_.json
  docs/docs/storages/supported-storages/_category_.json
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/img/docsVersionDropdown.png
  docs/docs/tutorial-extras/img/localeDropdown.png
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.js
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/src/pages/markdown-page.md
  docs/static/img/docusaurus-social-card.jpg
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/gluesql.jpg
  docs/static/img/logo.svg
Labels: improvement

#1217 Rewrite README.md for the new release
  README.md
  pkg/javascript/README.md
  pkg/javascript/package.json
Labels: documentation

#1224 Add test and doc for ast-builder::statements::querying::data-aggregation
  docs/docs/ast-builder/statements/querying/data-aggregation.md
  test-suite/src/ast_builder/mod.rs
  test-suite/src/ast_builder/statements/mod.rs
  test-suite/src/ast_builder/statements/querying/data_aggregation.rs
  test-suite/src/ast_builder/statements/querying/mod.rs
  test-suite/src/lib.rs
Labels: documentation

#1228 Write the blog article - breaking the boundary between sql and nosql …
  docs/blog/2023-05-29-breaking-the-boundary.md
Labels: documentation

#1229 Write the blog article - test driven documentation
  docs/blog/2023-05-30-test-driven-documentation.md
  docs/blog/assets/blog-test-driven-documentation-insert-errorcase.jpg
  docs/blog/assets/blog-test-driven-documentation-insert.jpg
Labels: documentation

#1231 Write the blog article - revolutionizing databases by unifying the qu…
  docs/blog/2023-05-30-revolutionizing-databases-by-unifying-query-interfaces.md
Labels: documentation

#1232 Update README.md - add blog article links
  README.md
  docs/docs/index.md
Labels: documentation

#1226 feat: fmt list and map
  core/src/data/value/convert.rs
Labels: improvement
