Repository gluesql/gluesql, pull requests merged in 2023-04, with the labels that each got.

#1096 Support Metadata trait
  Cargo.lock
  core/src/data/schema.rs
  core/src/executor/alter/table.rs
  core/src/executor/fetch.rs
  core/src/plan/mock.rs
  core/src/store/metadata.rs
  core/src/store/mod.rs
  storages/composite-storage/src/lib.rs
  storages/idb-storage/src/lib.rs
  storages/json-storage/src/lib.rs
  storages/memory-storage/src/lib.rs
  storages/memory-storage/src/metadata.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/shared-memory-storage/src/lib.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/lib.rs
  storages/sled-storage/tests/sled_storage.rs
  storages/web-storage/src/lib.rs
  test-suite/src/dictionary_index.rs
  test-suite/src/lib.rs
  test-suite/src/metadata/index.rs
  test-suite/src/metadata/mod.rs
  test-suite/src/metadata/table.rs
Labels: enhancement

#1135 Add JsonStorage support to CLI
  Cargo.lock
  README.md
  cli/Cargo.toml
  cli/src/lib.rs
Labels: enhancement

#1019 Add `UINT32`, `UINT64` and `UINT128` data types
  core/src/ast/data_type.rs
  core/src/data/bigdecimal_ext.rs
  core/src/data/interval/primitive.rs
  core/src/data/key.rs
  core/src/data/value/binary_op/decimal.rs
  core/src/data/value/binary_op/f64.rs
  core/src/data/value/binary_op/integer/macros.rs
  core/src/data/value/binary_op/integer/mod.rs
  core/src/data/value/binary_op/integer/u128.rs
  core/src/data/value/binary_op/integer/u32.rs
  core/src/data/value/binary_op/integer/u64.rs
  core/src/data/value/convert.rs
  core/src/data/value/error.rs
  core/src/data/value/expr.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/translate/data_type.rs
  test-suite/src/data_type/uint128.rs
  test-suite/src/data_type/uint32.rs
  test-suite/src/data_type/uint64.rs
Labels: enhancement

#1137 docs: add newly added data type into README.md
  README.md
Labels: documentation

#1130 Wrap identifiers with double qoute (`"`) at `to_sql`
  core/src/ast/ddl.rs
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast/mod.rs
  core/src/ast/operator.rs
  core/src/ast/query.rs
  core/src/ast_builder/select_item.rs
  core/src/data/schema.rs
  core/src/executor/fetch.rs
Labels: enhancement

#1139 Add unit tests for `TryFrom<&Value> for Decimal`
  core/src/data/value/convert.rs
Labels: improvement

#1143 fix : fix missing intg test for new data type
  test-suite/src/data_type/mod.rs
  test-suite/src/data_type/uint128.rs
  test-suite/src/data_type/uint32.rs
  test-suite/src/data_type/uint64.rs
  test-suite/src/lib.rs
Labels: improvement

#1064 add initcap function
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/initcap.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1095 Support user level sql function
  cli/src/command.rs
  cli/src/print.rs
  core/src/ast/ddl.rs
  core/src/ast/function.rs
  core/src/ast/mod.rs
  core/src/data/function.rs
  core/src/data/mod.rs
  core/src/executor/alter/error.rs
  core/src/executor/alter/function.rs
  core/src/executor/alter/mod.rs
  core/src/executor/alter/validate.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/execute.rs
  core/src/parse_sql.rs
  core/src/plan/expr/function.rs
  core/src/plan/mock.rs
  core/src/store/function.rs
  core/src/store/mod.rs
  core/src/translate/ddl.rs
  core/src/translate/error.rs
  core/src/translate/function.rs
  core/src/translate/mod.rs
  pkg/javascript/web/src/payload.rs
  storages/composite-storage/src/lib.rs
  storages/composite-storage/tests/error.rs
  storages/idb-storage/src/lib.rs
  storages/json-storage/src/function.rs
  storages/json-storage/src/lib.rs
  storages/memory-storage/src/lib.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/shared-memory-storage/src/lib.rs
  storages/shared-memory-storage/tests/shared_memory_storage.rs
  storages/sled-storage/src/lib.rs
  storages/web-storage/src/lib.rs
  test-suite/src/custom_function.rs
  test-suite/src/function/upper_lower.rs
  test-suite/src/lib.rs
Labels: enhancement

#1048 Implement geometric `POINT` Type and geometric functions
  core/src/ast/data_type.rs
  core/src/ast/function.rs
  core/src/data/key.rs
  core/src/data/mod.rs
  core/src/data/point.rs
  core/src/data/value/convert.rs
  core/src/data/value/error.rs
  core/src/data/value/expr.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/plan/expr/function.rs
  core/src/translate/data_type.rs
  core/src/translate/function.rs
  test-suite/src/data_type/mod.rs
  test-suite/src/data_type/point.rs
  test-suite/src/function/geometry/get_x.rs
  test-suite/src/function/geometry/get_y.rs
  test-suite/src/function/geometry/mod.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1132 Merge evaluate_stateless into evaluate,
  Cargo.lock
  core/src/data/interval/string.rs
  core/src/data/key.rs
  core/src/data/row.rs
  core/src/data/value/convert.rs
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  core/src/executor/aggregate/mod.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/alter/alter_table.rs
  core/src/executor/alter/function.rs
  core/src/executor/alter/table.rs
  core/src/executor/alter/validate.rs
  core/src/executor/context/row_context.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/executor/evaluate/stateless.rs
  core/src/executor/fetch.rs
  core/src/executor/insert.rs
  core/src/executor/limit.rs
  core/src/executor/mod.rs
  core/src/executor/select/mod.rs
  core/src/lib.rs
  core/src/mock.rs
  core/src/plan/join.rs
  core/src/plan/mod.rs
  core/src/plan/primary_key.rs
  core/src/plan/schema.rs
  core/src/plan/validate.rs
  core/src/result.rs
  core/src/store/data_row.rs
  storages/idb-storage/Cargo.toml
  storages/idb-storage/src/convert.rs
  storages/idb-storage/src/lib.rs
  storages/idb-storage/tests/convert.rs
  storages/json-storage/Cargo.toml
  storages/json-storage/src/lib.rs
  storages/memory-storage/src/alter_table.rs
  storages/sled-storage/Cargo.toml
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/index_sync.rs
  storages/sled-storage/src/store_mut.rs
  test-suite/src/migrate.rs
Labels: improvement

#1149 Add `PREPEND` function for `LIST` data type
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/prepend.rs
  test-suite/src/lib.rs
Labels: enhancement

#1151 Move the SCHEMA_PREFIX const into an impl in SledStorage
  storages/sled-storage/src/store.rs
Labels: improvement

#1153 Feat : add calc_distance function
  core/src/ast/function.rs
  core/src/data/point.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/geometry/calc_distance.rs
  test-suite/src/function/geometry/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1161 fix: typo
  core/src/ast/expr.rs
  core/src/ast/query.rs
  core/src/data/key.rs
Labels: improvement

#1155 Write docs/ Developing Custom Storages contents
  docs/docs/storages/developing-custom-storages/intro.md
  docs/docs/storages/developing-custom-storages/store-traits/alter-table.md
  docs/docs/storages/developing-custom-storages/store-traits/custom-function-mut.md
  docs/docs/storages/developing-custom-storages/store-traits/custom-function.md
  docs/docs/storages/developing-custom-storages/store-traits/index-mut.md
  docs/docs/storages/developing-custom-storages/store-traits/index-trait.md
  docs/docs/storages/developing-custom-storages/store-traits/metadata.md
  docs/docs/storages/developing-custom-storages/store-traits/store-mut.md
  docs/docs/storages/developing-custom-storages/store-traits/store.md
  docs/docs/storages/developing-custom-storages/store-traits/transaction.md
  docs/docs/storages/developing-custom-storages/using-test-suite.md
Labels: documentation

#1159 Write docs/getting-started/javascript-web.md
  docs/docs/getting-started/javascript-web.md
  docs/docs/getting-started/rust.md
  docs/docs/getting-started/web/_category_.json
  docs/docs/getting-started/web/modules.md
  docs/docs/getting-started/web/rollup.md
  docs/docs/getting-started/web/supported-storages.md
  docs/docs/getting-started/web/webpack.md
Labels: documentation
