Repository gluesql/gluesql, pull requests merged in 2023-10, with the labels that each got.

#1419 Change store RowIter type from Iterator to Stream
  Cargo.lock
  cli/Cargo.toml
  cli/src/lib.rs
  core/src/executor/fetch.rs
  core/src/executor/validate.rs
  core/src/store/mod.rs
  storages/composite-storage/tests/error.rs
  storages/csv-storage/Cargo.toml
  storages/csv-storage/src/lib.rs
  storages/csv-storage/src/store.rs
  storages/idb-storage/src/lib.rs
  storages/json-storage/src/lib.rs
  storages/json-storage/src/store.rs
  storages/memory-storage/Cargo.toml
  storages/memory-storage/src/lib.rs
  storages/memory-storage/tests/memory_storage.rs
  storages/shared-memory-storage/tests/shared_memory_storage.rs
  storages/sled-storage/Cargo.toml
  storages/sled-storage/src/index.rs
  storages/sled-storage/src/index_mut.rs
  storages/sled-storage/src/store.rs
  storages/web-storage/Cargo.toml
  storages/web-storage/src/lib.rs
Labels: improvement

#1357 feat: Implement python binding
  .github/workflows/python.yml
  .gitignore
  Cargo.toml
  pkg/python/Cargo.toml
  pkg/python/DEVELOPMENT.md
  pkg/python/examples/json-storage/fixtures/test.json
  pkg/python/examples/json-storage/main.py
  pkg/python/examples/memory-storage/main.py
  pkg/python/examples/shared-memory-storage/main.py
  pkg/python/examples/sled-storage/main.py
  pkg/python/gluesql.pyi
  pkg/python/pyproject.toml
  pkg/python/pytest.ini
  pkg/python/requirements.txt
  pkg/python/src/error.rs
  pkg/python/src/lib.rs
  pkg/python/src/payload.rs
  pkg/python/src/storages.rs
  pkg/python/tests/payload.py
  storages/json-storage/src/lib.rs
Labels: enhancement

#1423 docs:Add doc about SPLICE function
  docs/docs/sql-syntax/functions/list-map/splice.md
Labels: documentation

#1424 test: add cases to character_conversion
  test-suite/src/ast_builder/function/text/character_conversion.rs
  test-suite/src/ast_builder/function/text/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1425 docs: Add `SLICE` function doc
  docs/docs/sql-syntax/functions/list-map/slice.md
Labels: documentation

#1429 feat: implement `select` iterator utility function
  core/src/executor/execute.rs
  pkg/rust/examples/hello_world.rs
Labels: enhancement

#1428 write docmentation for character_conversion
  docs/docs/ast-builder/functions/text/character-conversion.md
Labels: documentation

#1430 Implement DEDUP function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/dedup.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1355 feat: add index_by node
  core/src/ast_builder/index_item/cmp_expr.rs
  core/src/ast_builder/index_item/mod.rs
  core/src/ast_builder/index_item/non_clustered.rs
  core/src/ast_builder/index_item/primary_key.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/root.rs
  core/src/ast_builder/table_factor.rs
  core/src/ast_builder/table_name.rs
  test-suite/src/ast_builder/index_by.rs
  test-suite/src/ast_builder/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1436 Update docs/ast-builder padding.md code block lang keyword,
  docs/docs/ast-builder/functions/text/padding.md
Labels: documentation
