Repository gluesql/gluesql, pull requests merged in 2023-07, with the labels that each got.

#1267 Implement CAST text literal or value to MAP or LIST,
  core/src/data/value/literal.rs
  core/src/data/value/mod.rs
  test-suite/src/data_type/list.rs
  test-suite/src/data_type/map.rs
Labels: improvement

#1266 [Function] Implement REPLACE function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/replace.rs
  test-suite/src/lib.rs
Labels: enhancement

#1275 feat: implement `ast_builder` for replace function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1283 [Function] Implement TAKE function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/take.rs
  test-suite/src/lib.rs
Labels: enhancement

#1292 Upgrade sqlparser-rs version to 0.35,
  Cargo.lock
  core/Cargo.toml
  core/src/translate/error.rs
  core/src/translate/expr.rs
  core/src/translate/mod.rs
  core/src/translate/query.rs
Labels: improvement

#1284 Fix Scala Subquery should contain only 1 column
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/mod.rs
  test-suite/src/project.rs
Labels: bug

#1298 feat: implement `LENGTH` function
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/length.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1313 Update auto-assign-action to be triggered on PR open from fork repos
  .github/workflows/auto-author-assign.yml
Labels: bug

#1314 Fix spool on `tabular off` and `SelectMap`
  cli/src/print.rs
Labels: bug

#1286 Implement BIT_SHIFT_LEFT operation
  core/src/ast/operator.rs
  core/src/ast_builder/expr/binary_op.rs
  core/src/data/literal.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/translate/operator.rs
  test-suite/src/bitwise_shift.rs
  test-suite/src/lib.rs
Labels: enhancement

#1281 Feat: impl bitwise-and operation
  core/src/ast/operator.rs
  core/src/ast_builder/expr/binary_op.rs
  core/src/data/literal.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/translate/operator.rs
  test-suite/src/arithmetic/error.rs
  test-suite/src/bitwise_and.rs
  test-suite/src/function/substr.rs
  test-suite/src/lib.rs
Labels: enhancement

#1288 Implement VALUES function for Map type
  core/src/ast/function.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/values.rs
  test-suite/src/lib.rs
Labels: enhancement

#1325 Implement Skip function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/skip.rs
  test-suite/src/lib.rs
Labels: enhancement

#1321 Feature/operator bit not
  core/src/ast/operator.rs
  core/src/data/value/error.rs
  core/src/data/value/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/translate/operator.rs
  test-suite/src/function/substr.rs
  test-suite/src/unary_operator.rs
Labels: enhancement

#1315 Implement ENTRIES function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/entries.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1331 Refactor GCD and LCM functions
  core/src/data/value/error.rs
  core/src/executor/evaluate/function.rs
  docs/docs/sql-syntax/functions/math/gcd.md
  docs/docs/sql-syntax/functions/math/lcm.md
  test-suite/src/function/gcd_lcm.rs
Labels: improvement

#1337 Implement ast_builder for is_empty function
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1323 Implement LAST_DAY function #1315
  core/src/ast/function.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/last_day.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1344 Implement last_day function in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1346 feat: Implement take function in ast_builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement
