Repository gluesql/gluesql, pull requests merged in 2023-08, with the labels that each got.

#1359 Add ExprWithAliasNode to ast builder
  core/src/ast_builder/expr/alias_as.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/expr_with_alias.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select_item.rs
  core/src/ast_builder/select_item_list.rs
Labels: enhancement

#1352 Fix Value::evaluate_cmp_with_literal between Decimal and Literal::Num…
  core/src/data/value/literal.rs
  test-suite/src/data_type/decimal.rs
Labels: bug

#1365 feat: Implement select without table function in ast_builder
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/root.rs
Labels: enhancement

#1333 Implement COALESCE function
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/ast_builder/function/other/coalesce.rs
  test-suite/src/ast_builder/function/other/mod.rs
  test-suite/src/function/coalesce.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1366 Implement bitwise-not operator (~) in ast builder
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/expr/unary_op.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1312 Implement GREATEST function
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/greatest.rs
  test-suite/src/function/mod.rs
  test-suite/src/lib.rs
Labels: enhancement

#1367 fix: update Key.cmp to compare a type with other type
  core/src/data/key.rs
  test-suite/src/function/values.rs
Labels: bug

#1364 Implement entries in ast builder
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/mod.rs
Labels: enhancement

#1374 Update Chrono version to 0.4.26,
  Cargo.lock
  core/Cargo.toml
Labels: improvement

#1340 Implement `SLICE` function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/slice.rs
  test-suite/src/lib.rs
Labels: enhancement

#1379 chore: add example of convert from payload to custom struct
  README.md
  pkg/rust/examples/hello_world.rs
Labels: documentation, improvement

#1371 Implement `SPLICE` function
  core/src/ast/function.rs
  core/src/executor/evaluate/function.rs
  core/src/executor/evaluate/mod.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function/mod.rs
  test-suite/src/function/splice.rs
  test-suite/src/lib.rs
Labels: enhancement

#1388 chore: bump rust versino to 1.72
  Cargo.toml
  cli/src/cli.rs
  cli/src/helper.rs
  core/src/ast/query.rs
  core/src/executor/aggregate/mod.rs
  core/src/plan/expr/mod.rs
  core/src/translate/expr.rs
  rust-toolchain
  storages/csv-storage/src/lib.rs
  storages/json-storage/src/store_mut.rs
  storages/memory-storage/src/alter_table.rs
  storages/sled-storage/src/key.rs
Labels: improvement
