Repository gluesql/gluesql, pull requests merged in 2024-06, with the labels that each got.

#1504 Fix panic in SledStorage tx_timeout calculation by re-arranging terms
  storages/sled-storage/src/lock.rs
Labels: bug

#1400 Support Foreign key constraint
  Cargo.lock
  core/src/ast/mod.rs
  core/src/ast_builder/create_table.rs
  core/src/ast_builder/drop_table.rs
  core/src/ast_builder/table_name.rs
  core/src/data/schema.rs
  core/src/executor/alter/alter_table.rs
  core/src/executor/alter/error.rs
  core/src/executor/alter/mod.rs
  core/src/executor/alter/table.rs
  core/src/executor/delete.rs
  core/src/executor/execute.rs
  core/src/executor/insert.rs
  core/src/executor/mod.rs
  core/src/executor/update.rs
  core/src/mock.rs
  core/src/result.rs
  core/src/store/mod.rs
  core/src/translate/error.rs
  core/src/translate/mod.rs
  storages/csv-storage/src/lib.rs
  storages/csv-storage/src/store.rs
  storages/json-storage/src/lib.rs
  storages/mongo-storage/src/column_description.rs
  storages/mongo-storage/src/description.rs
  storages/mongo-storage/src/lib.rs
  storages/mongo-storage/src/store.rs
  storages/mongo-storage/src/store_mut.rs
  storages/mongo-storage/src/utils.rs
  storages/mongo-storage/tests/mongo_indexes.rs
  storages/mongo-storage/tests/mongo_types.rs
  storages/parquet-storage/Cargo.toml
  storages/parquet-storage/src/lib.rs
  storages/parquet-storage/src/store_mut.rs
  storages/sled-storage/src/alter_table.rs
  storages/sled-storage/src/index_mut.rs
  test-suite/src/alter/alter_table.rs
  test-suite/src/foreign_key.rs
  test-suite/src/lib.rs
  test-suite/src/store/insert_schema.rs
Labels: enhancement

#1507 Refactor SledStorage::new to accept AsRef<Path> for filename parameter
  storages/sled-storage/src/lib.rs
Labels: improvement
