Repository gluesql/gluesql, pull requests merged in 2024-08, with the labels that each got.

#1527 Reformatted imports
  core/src/ast_builder/expr/function.rs
  core/src/ast_builder/expr/mod.rs
  core/src/ast_builder/index.rs
  core/src/ast_builder/index_item/mod.rs
  core/src/ast_builder/mod.rs
  core/src/ast_builder/select/mod.rs
  core/src/ast_builder/select/values.rs
  core/src/data/interval/mod.rs
  core/src/executor/fetch.rs
  storages/csv-storage/src/store_mut.rs
  storages/json-storage/src/store_mut.rs
  storages/mongo-storage/src/row/value.rs
  storages/parquet-storage/tests/schema.rs
  storages/redis-storage/tests/redis_store.rs
  test-suite/src/alter/mod.rs
  test-suite/src/ast_builder/function/datetime/conversion.rs
  test-suite/src/ast_builder/function/datetime/mod.rs
  test-suite/src/function/cast.rs
  test-suite/src/function/last_day.rs
  test-suite/src/function/md5.rs
  test-suite/src/function/take.rs
  test-suite/src/schemaless/mod.rs
  test-suite/src/transaction/mod.rs
Labels: improvement

#1529 FileStorage
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/lib.rs
  pkg/rust/Cargo.toml
  pkg/rust/src/lib.rs
  storages/file-storage/Cargo.toml
  storages/file-storage/src/lib.rs
  storages/file-storage/src/store.rs
  storages/file-storage/src/store_mut.rs
  storages/file-storage/tests/file_storage.rs
Labels: enhancement

#1532 GitStorage
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  storages/git-storage/Cargo.toml
  storages/git-storage/src/lib.rs
  storages/git-storage/src/store.rs
  storages/git-storage/src/store_mut.rs
  storages/git-storage/tests/git_storage_csv.rs
  storages/git-storage/tests/git_storage_file.rs
  storages/git-storage/tests/git_storage_json.rs
  storages/git-storage/tests/pull_and_push.rs
Labels: enhancement

#1534 Add CSV Storage docs to README.md & Docs
  README.md
  docs/docs/storages/supported-storages/composite-storage.md
  docs/docs/storages/supported-storages/csv-storage.md
  docs/docs/storages/supported-storages/idb-storage.md
  docs/docs/storages/supported-storages/json-storage.md
  docs/docs/storages/supported-storages/memory-storage.md
  docs/docs/storages/supported-storages/parquet-storage.md
  docs/docs/storages/supported-storages/shared-memory-storage.md
  docs/docs/storages/supported-storages/sled-storage.md
  docs/docs/storages/supported-storages/web-storage.md
  docs/package-lock.json
Labels: documentation

#1543 Update README.md & docs/index - add file & git storages
  README.md
  docs/docs/index.md
Labels: documentation

#1549 Fix publish-rust.yml GitHub Action - make publish sequential
  .github/workflows/publish-rust.yml
Labels: bug

#1556 Fix GitStorage gh-action env uses
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
Labels: bug

#1557 Fix GitStorage GitHub Action to run in forks
  .github/workflows/coverage.yml
  .github/workflows/rust.yml
  storages/git-storage/tests/pull_and_push.rs
Labels: bug

#1564 Fix publish-rust.yml gh action to use token correctly
  .github/workflows/publish-rust.yml
Labels: bug
