Repository gluesql/gluesql, pull requests merged in 2025-07, with the labels that each got.

#1665 Ensure table names are quoted in INSERT statement to_sql output
  core/src/ast.rs
Labels: codex

#1670 Update comments in gluesql-js web example README
  pkg/javascript/examples/web/module/README.md
Labels: documentation

#1662 Move ValueError cases in evaluate module to EvaluateError variants
  core/src/data/value/error.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  test-suite/src/function/add_month.rs
  test-suite/src/function/concat.rs
  test-suite/src/function/gcd_lcm.rs
Labels: codex

#1677 Add CURRENT_DATE, CURRENT_TIME, and CURRENT_TIMESTAMP functions
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/executor/evaluate.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function.rs
  test-suite/src/function/current_date.rs
  test-suite/src/function/current_time.rs
  test-suite/src/function/current_timestamp.rs
  test-suite/src/lib.rs
Labels: enhancement

#1681 [Document] docusaurus version update
  docs/blog/2023-05-27-release-v0.14.md
  docs/blog/2023-11-18-release-v0.15.md
  docs/docs/getting-started/cli.md
  docs/docs/index.md
  docs/docs/storages/supported-storages/parquet-storage.md
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: improvement

#1659 Refactor OrStream size_hint and add tests
  utils/src/or_stream.rs
Labels: codex

#1660 Add conflict errors to MongoStorageError
  storages/mongo-storage/src/error.rs
  storages/mongo-storage/src/store.rs
  storages/mongo-storage/src/store_mut.rs
  storages/mongo-storage/tests/mongo_storage_conflict.rs
Labels: codex

#1667 Fix single quotes escaping in AstLiteral::QuotedString
  core/src/ast/ast_literal.rs
Labels: codex

#1679 Update publish-docs gh-action to change default doc redirect path
  .github/workflows/publish-docs.yml
Labels: codex
