Repository gluesql/gluesql, pull requests merged in 2025-09, with the labels that each got.

#1765 Rename coverage publish workflow and simplify timestamp
  .github/workflows/publish-coverage.yml
Labels: codex

#1763 Publish coverage report to gluesql.org/coverage
  .github/workflows/coverage.yml
  .github/workflows/publish-coverage.yml
Labels: codex

#1773 Fix publish-coverage action - artifact download & PR comment
  .github/workflows/publish-coverage.yml
Labels: bug

#1776 Bump redis crate to v0.32 in RedisStorage
  Cargo.lock
  storages/redis-storage/Cargo.toml
Labels: codex

#1782 Remove async from redb storage core
  storages/redb-storage/src/core.rs
  storages/redb-storage/src/lib.rs
Labels: codex

#1783 Update web storage dependencies
  Cargo.lock
  storages/web-storage/Cargo.toml
Labels: codex

#1784 Update existing PR coverage comment instead of creating new one
  .github/workflows/publish-coverage.yml
Labels: codex

#1787 Add TRUNC function support
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/executor/evaluate.rs
  core/src/executor/evaluate/function.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  docs/docs/sql-syntax/functions/math/trunc.md
  test-suite/src/ast_builder/function/math/rounding.rs
  test-suite/src/function.rs
  test-suite/src/function/trunc.rs
  test-suite/src/lib.rs
Labels: enhancement

#1788 Update AGENTS.md to document grouped use convention
  AGENTS.md
Labels: documentation, codex

#1802 Remove release drafter GitHub Action
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: codex

#1804 Include gluesql-macros in publish workflow
  .github/workflows/publish-rust.yml
Labels: codex
