Repository gluesql/gluesql, pull requests merged in 2025-08, with the labels that each got.

#1683 Add NULLIF functions
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/executor/evaluate.rs
  core/src/executor/evaluate/function.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/ast_builder/function/other.rs
  test-suite/src/ast_builder/function/other/nullif.rs
  test-suite/src/function.rs
  test-suite/src/function/nullif.rs
  test-suite/src/lib.rs
Labels: enhancement

#1693 Enable wasm32 build for idb storage
  Cargo.lock
  storages/idb-storage/Cargo.toml
  storages/idb-storage/src/error.rs
  storages/idb-storage/src/lib.rs
Labels: codex

#1695 test: add len and is_empty tests for Vector
  utils/src/vector.rs
Labels: codex

#1698 Simplify plan function generic bounds
  core/src/plan.rs
Labels: codex

#1703 remove send sync constraint from customfunctionmut
  core/src/store/function.rs
Labels: codex

#1704 Remove Send Sync bounds from Transaction trait
  core/src/store/transaction.rs
Labels: codex

#1694 Add HEX function
  core/src/ast/function.rs
  core/src/ast_builder/expr/function.rs
  core/src/executor/evaluate.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/evaluate/function.rs
  core/src/plan/expr/function.rs
  core/src/translate/function.rs
  test-suite/src/function.rs
  test-suite/src/function/hex.rs
  test-suite/src/lib.rs
Labels: enhancement

#1715 Add RedisStorage tests to cover alter table storage errors
  storages/redis-storage/src/alter_table.rs
  storages/redis-storage/tests/redis_alter_table_errors.rs
Labels: codex

#1709 Add tests for aggregate BETWEEN and CASE expressions
  test-suite/src/aggregate.rs
  test-suite/src/aggregate/expr.rs
  test-suite/src/lib.rs
Labels: codex

#1685 Evaluate expressions to NULL when any operand is NULL
  core/src/executor/evaluate.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  core/src/executor/filter.rs
  test-suite/src/data_type.rs
  test-suite/src/data_type/null.rs
  test-suite/src/expr.rs
  test-suite/src/expr/between.rs
  test-suite/src/expr/in_list.rs
  test-suite/src/lib.rs
Labels: improvement

#1726 Fix Redis storage test connection handling
  storages/redis-storage/tests/redis_alter_table_errors.rs
Labels: codex

#1705 Change the return type of evaluate_eq
  core/src/data/literal.rs
  core/src/data/value.rs
  core/src/data/value/json.rs
  core/src/data/value/literal.rs
  core/src/executor/evaluate.rs
  core/src/executor/evaluate/evaluated.rs
  core/src/executor/evaluate/expr.rs
  utils/src/lib.rs
  utils/src/tribool.rs
Labels: improvement

#1710 Implement `DISTINCT` operations
  core/src/ast.rs
  core/src/ast/expr.rs
  core/src/ast/function.rs
  core/src/ast/query.rs
  core/src/ast_builder.rs
  core/src/ast_builder/expr/aggregate.rs
  core/src/ast_builder/expr/in_list.rs
  core/src/ast_builder/query.rs
  core/src/ast_builder/select/filter.rs
  core/src/ast_builder/select/group_by.rs
  core/src/ast_builder/select/join/hash_join.rs
  core/src/ast_builder/select/join/join_constraint.rs
  core/src/ast_builder/select/join/root.rs
  core/src/ast_builder/select/limit.rs
  core/src/ast_builder/select/offset.rs
  core/src/ast_builder/select/order_by.rs
  core/src/ast_builder/select/project.rs
  core/src/ast_builder/select/root.rs
  core/src/executor/aggregate/state.rs
  core/src/executor/evaluate/error.rs
  core/src/executor/execute.rs
  core/src/executor/select.rs
  core/src/plan/evaluable.rs
  core/src/plan/expr/aggregate.rs
  core/src/plan/index.rs
  core/src/plan/join.rs
  core/src/plan/primary_key.rs
  core/src/plan/schema.rs
  core/src/translate/error.rs
  core/src/translate/function.rs
  core/src/translate/query.rs
  test-suite/src/aggregate/avg.rs
  test-suite/src/aggregate/count.rs
  test-suite/src/aggregate/max.rs
  test-suite/src/aggregate/min.rs
  test-suite/src/aggregate/stdev.rs
  test-suite/src/aggregate/sum.rs
  test-suite/src/aggregate/variance.rs
  test-suite/src/ast_builder/select.rs
  test-suite/src/ast_builder/statements/querying/data_aggregation.rs
  test-suite/src/distinct.rs
  test-suite/src/inline_view.rs
  test-suite/src/lib.rs
  test-suite/src/migrate.rs
Labels: enhancement

#1746 Remove ast::Statement ToSql trait implementation
  cli/src/lib.rs
  core/src/ast.rs
  core/src/data/schema.rs
Labels: codex

#1748 Remove unused tester run function
  test-suite/src/tester.rs
Labels: codex

#1751 Cover fetch_all_schemas error in MockStorage unit tests
  core/src/mock.rs
Labels: codex

#1752 Update AGENTS.md - remind to run relevant tests
  AGENTS.md
Labels: codex

#1757 Update coverage.yml to run on GitHub-hosted runner
  .github/workflows/coverage.yml
Labels: codex
